// Atualizado: 18/03/2026 17:17
const CAR_DATA = [
  {
    "id": "DVAzVXWAEuU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Oferta R$40.000",
    "description": "Oferta R$40.000\n\nREPASSE\n\nCIVIC SEDAN EXS 1.8\nKm 150 mil\nAno 2010\n\nFipe\nR$53.118,00\n\nPor\nR$40.000,00\nIpva 2026 em\nAberto",
    "price": "R$40.000",
    "image": "imagens/autopar.repasses_DVAzVXWAEuU.jpg",
    "url": "https://www.instagram.com/p/DVAzVXWAEuU/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "oferta",
      "r$40.000",
      "repasse",
      "civic",
      "sedan",
      "2010",
      "fipe",
      "r$53.118,00",
      "r$40.000,00",
      "ipva",
      "2026",
      "aberto"
    ]
  },
  {
    "id": "DVAyP9ogHTn",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vera Cruz 7 lugares",
    "description": "Vera Cruz 7 lugares\nV6!\nAno 2008\nFipe 47.000\nValor 28.990 pra torrar!\n18 mil abaixo ds fipe!\nCom teto solar.\nZero para andar.\nMecânica em dia , (\ncliente gastou 8.000 e vai me mandar as notas\nInterna bancos dianteiros com couro pouco desgastados.\nCarro muito filé para andar.\nCarro é revisado, mas mesmo assim não vendemos Carro com garantia.",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVAyP9ogHTn.jpg",
    "url": "https://www.instagram.com/p/DVAyP9ogHTn/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "vera",
      "cruz",
      "lugares",
      "2008",
      "fipe",
      "47.000",
      "valor",
      "28.990",
      "torrar!",
      "abaixo",
      "fipe!",
      "teto",
      "solar.",
      "zero",
      "para",
      "andar.",
      "mecânica",
      "cliente",
      "gastou",
      "8.000",
      "mandar",
      "notas",
      "interna",
      "bancos",
      "dianteiros"
    ]
  },
  {
    "id": "DV52BROgDRS",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "AUTOPAR REPASSES",
    "description": "AUTOPAR REPASSES\n\nFORD TERRITORY\nTITANIUM\n\nANO 2021\nKm 94.000\nFipe R$118.882,00\nRepasse por R$100.000\n\nSem leilão sem sinistro\nVistoria cautelar apv",
    "price": "R$118.882,00",
    "image": "imagens/autopar.repasses_DV52BROgDRS.jpg",
    "url": "https://www.instagram.com/p/DV52BROgDRS/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "ford",
      "territory",
      "titanium",
      "2021",
      "94.000",
      "fipe",
      "r$118.882,00",
      "repasse",
      "r$100.000",
      "leilão",
      "sinistro",
      "vistoria",
      "cautelar"
    ]
  },
  {
    "id": "DV5tEWYAJrY",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "AUTOPAR REPASSES",
    "description": "AUTOPAR REPASSES\n\nCOROLLA XEI 2.0\nKm 130 mil\n2012\n\nTrocar 2 pneus\n1 pára-brisa\n\nCautelar aprovada\nSem leilão sem sinistro\n\nCarro bom\n\nFipe\nR$63.000\nPor 55.000\n\nCarro bom",
    "price": "R$63.000",
    "image": "imagens/autopar.repasses_DV5tEWYAJrY.jpg",
    "url": "https://www.instagram.com/p/DV5tEWYAJrY/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "corolla",
      "2012",
      "trocar",
      "pneus",
      "pára-brisa",
      "cautelar",
      "aprovada",
      "leilão",
      "sinistro",
      "carro",
      "fipe",
      "r$63.000",
      "55.000",
      "carro"
    ]
  },
  {
    "id": "DVWEZeWAGoW",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "OFERTA DE RESPASSE",
    "description": "OFERTA DE RESPASSE\nVANTAGEM COMERCIAL\n\nAUTOPAR REPASSES\n\nONIX LT TURBO\n2025\n\nSem leilão sem sinistro\nCautelar aprovará\nDoc 2026 quitado\n4 pneus ótimos\nAr gelado\nCâmera de ré\n\nFazer\nBico do capô\nPára-choque dianteiro\nRisco leve no pára-lama\n\nMargem de 15.852\n\nFipe R$85.850\nPor R$70.000\nTed ou pix\n\n#repasses #autoparrepasses #curitiba\n#brasil🇧🇷 #abaixodafipe",
    "price": "R$85.850",
    "image": "imagens/autopar.repasses_DVWEZeWAGoW.jpg",
    "url": "https://www.instagram.com/p/DVWEZeWAGoW/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "oferta",
      "respasse",
      "vantagem",
      "comercial",
      "autopar",
      "repasses",
      "onix",
      "turbo",
      "2025",
      "leilão",
      "sinistro",
      "cautelar",
      "aprovará",
      "2026",
      "quitado",
      "pneus",
      "ótimos",
      "gelado",
      "câmera",
      "fazer",
      "bico",
      "capô",
      "pára-choque",
      "dianteiro",
      "risco"
    ]
  },
  {
    "id": "DVAxOxKgBng",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "AUTOPAR REPASSES",
    "description": "AUTOPAR REPASSES\n\nBiz 125 ks\n2011\nKm 40 mil\n\nFipe R$9.500\n\nPor 8.300",
    "price": "R$9.500",
    "image": "imagens/autopar.repasses_DVAxOxKgBng.jpg",
    "url": "https://www.instagram.com/p/DVAxOxKgBng/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "2011",
      "fipe",
      "r$9.500",
      "8.300"
    ]
  },
  {
    "id": "DT_lReIgH-9",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nAUTOPAR REPASSES\nRua OMILIO MONTEIRO SOARES 1686 Fanny Curitiba Paraná\n\n(41)9.9104-4503\nJociel\n(41)9.9104-4302\nRoniel\n\nOportunidade\n\nTucson\n\nFipe 38.000\n\nValor 25.000 mil\n\nDespesa 2 peças pra pintar\n\nSuspensão bate a frente\n\nAr não gela\n\nSem leilão\n\nSem sinistro\n\nIpva 2026 pago",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DT_lReIgH-9.jpg",
    "url": "https://www.instagram.com/p/DT_lReIgH-9/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "autopar",
      "repasses",
      "omilio",
      "monteiro",
      "soares",
      "1686",
      "fanny",
      "curitiba",
      "paraná",
      "(41)9.9104-4503",
      "jociel",
      "(41)9.9104-4302",
      "roniel",
      "oportunidade",
      "tucson",
      "fipe",
      "38.000",
      "valor",
      "25.000",
      "despesa",
      "peças",
      "pintar",
      "suspensão",
      "bate"
    ]
  },
  {
    "id": "DV5t_NLgLyW",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "REPASSE",
    "description": "REPASSE\n\nFIAT STRADA ENDURENCE 1.4 flex\n\nTem detalhes\n\nDoc 2026 pago\n\nSem leilão sem sinistro\nCautelar aprovada\n\nAr gela\nBoa pra andar\n\nTrocar pára-choque\nPintar 3 peças\n\nFipe\nR$70.000\nPor R$51.000",
    "price": "R$70.000",
    "image": "imagens/autopar.repasses_DV5t_NLgLyW.jpg",
    "url": "https://www.instagram.com/p/DV5t_NLgLyW/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "repasse",
      "fiat",
      "strada",
      "endurence",
      "flex",
      "detalhes",
      "2026",
      "pago",
      "leilão",
      "sinistro",
      "cautelar",
      "aprovada",
      "gela",
      "andar",
      "trocar",
      "pára-choque",
      "pintar",
      "peças",
      "fipe",
      "r$70.000",
      "r$51.000"
    ]
  },
  {
    "id": "DVaDKmyABTU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "R$20.000 de margem",
    "description": "R$20.000 de margem",
    "price": "R$20.000",
    "image": "imagens/autopar.repasses_DVaDKmyABTU.jpg",
    "url": "https://www.instagram.com/p/DVaDKmyABTU/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "r$20.000",
      "margem"
    ]
  },
  {
    "id": "DVzfLXAAO1d",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Tracker premier",
    "description": "Tracker premier\n\nMotor 1.4 turbo 4 cilindros\n\nFipe 84.000 mil\n\nValor 67.000 mil\n\nConsta rs no dok\n\nMas tem aparência",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVzfLXAAO1d.jpg",
    "url": "https://www.instagram.com/p/DVzfLXAAO1d/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "tracker",
      "premier",
      "motor",
      "turbo",
      "cilindros",
      "fipe",
      "84.000",
      "valor",
      "67.000",
      "consta",
      "aparência"
    ]
  },
  {
    "id": "DVWAA0OALyX",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nREPASSE NO ESTADO\n\nAUTOPAR REPASSES\n\nVOLKSWAGEN SAVEIRO ROBUST\nMOTOR 1.6 flex\nKm 60 mil\n\n✅ Sem leilão sem sinistro\n\nTem detalhes por isso a marge tão alta\nLataria\nCapa de Lama\nLavagem e polimento\nEscape furado\n\n✅ Ar gela\n✅ Pneus bons\n✅ Doc 2026 pg\n\nTabela Fipe\nR$78.000\nPor\nR$56.000\n\nRua OMILIO MONTEIRO SOARES 1686 Fanny Curitiba Paraná\n(41)9.9104-4503\n\n#repasses #veiculousado #curitiba #a",
    "price": "R$78.000",
    "image": "imagens/autopar.repasses_DVWAA0OALyX.jpg",
    "url": "https://www.instagram.com/p/DVWAA0OALyX/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "repasse",
      "estado",
      "autopar",
      "repasses",
      "volkswagen",
      "saveiro",
      "robust",
      "motor",
      "flex",
      "leilão",
      "sinistro",
      "detalhes",
      "isso",
      "marge",
      "alta",
      "lataria",
      "capa",
      "lama",
      "lavagem",
      "polimento",
      "escape",
      "furado",
      "gela",
      "pneus"
    ]
  },
  {
    "id": "DT_pVIGgNtW",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nChevrolet ônix\n\nAno 2023\nVersão LT2\nKm100 mil único dono\n\nMultimídia\nRodas de liga leve\nChave de prensenca\n\nFipe 66.000\n\nValor 52.000 mil\n\nIpva 2026 já está pago integral\n\nCarro de único dono\n\nApenas retocar 2 pára-choque\n\nNão é batido aprova em\nPerícia",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DT_pVIGgNtW.jpg",
    "url": "https://www.instagram.com/p/DT_pVIGgNtW/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "chevrolet",
      "ônix",
      "2023",
      "versão",
      "km100",
      "único",
      "dono",
      "multimídia",
      "rodas",
      "liga",
      "leve",
      "chave",
      "prensenca",
      "fipe",
      "66.000",
      "valor",
      "52.000",
      "ipva",
      "2026",
      "está",
      "pago",
      "integral",
      "carro",
      "único"
    ]
  },
  {
    "id": "DV5456xgNJI",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "AUTOPAR REPASSES",
    "description": "AUTOPAR REPASSES\n\nJEEP COMPASS\nLONG 2.0 FLEX\n\nAno/18\nBRANCA\nKm 134.000\nFipe 89.490,00\nRepasse 76.000\n\nCautelar aprovada",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DV5456xgNJI.jpg",
    "url": "https://www.instagram.com/p/DV5456xgNJI/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "jeep",
      "compass",
      "long",
      "flex",
      "ano/18",
      "branca",
      "134.000",
      "fipe",
      "89.490,00",
      "repasse",
      "76.000",
      "cautelar",
      "aprovada"
    ]
  },
  {
    "id": "DVAtihfgPwU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Jetta 2.0 aspirado",
    "description": "Jetta 2.0 aspirado\nComfortline\n\nAno 2014\nKm 200 registro 160\n\nTrocar capo\nÉ um pára-lama\n\nPneus bons\n\nNão tem leilão\nNão tem sinistro\n\nFipe 65.000\n\nValor 50.000\n\nInterna boa\n\nMotor e câmbio é bom\n\nIpva 26 2 parcelas pagas\nRestante vai em\nAberto",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVAtihfgPwU.jpg",
    "url": "https://www.instagram.com/p/DVAtihfgPwU/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "jetta",
      "aspirado",
      "comfortline",
      "2014",
      "registro",
      "trocar",
      "capo",
      "pára-lama",
      "pneus",
      "bons",
      "leilão",
      "sinistro",
      "fipe",
      "65.000",
      "valor",
      "50.000",
      "interna",
      "motor",
      "câmbio",
      "ipva",
      "parcelas",
      "pagas",
      "restante",
      "aberto"
    ]
  },
  {
    "id": "DUg3SR_AFAy",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vw t-cross",
    "description": "Vw t-cross\nAno 2020\nFipe 105.500\nValor 95.000 mil\nHighline 1.4\nKm 118 mil\nSem leilão\nSem sinistro\nCautelar aprovada\nPneus bons\nInterna zera\nDe lata 1 peça pra pintar",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DUg3SR_AFAy.jpg",
    "url": "https://www.instagram.com/p/DUg3SR_AFAy/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "t-cross",
      "2020",
      "fipe",
      "105.500",
      "valor",
      "95.000",
      "highline",
      "leilão",
      "sinistro",
      "cautelar",
      "aprovada",
      "pneus",
      "bons",
      "interna",
      "zera",
      "lata",
      "peça",
      "pintar"
    ]
  },
  {
    "id": "DT_nZFngDdc",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\nHonda fit\n\nCarro de cliente não vai ficar muito tempo por aqui consultar antes de vir\n\nHonda fit\n\nAno 2009\n\nFipe 39.000\n\nValor 25.000 mil\n\n❌Tem rs no dok❌\n\nDetalhado em vídeo\n\nHigienizar interna\n\nAr não gela\n\nPara brisa trincado\n\nSuspensão boa",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DT_nZFngDdc.jpg",
    "url": "https://www.instagram.com/p/DT_nZFngDdc/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "honda",
      "carro",
      "cliente",
      "ficar",
      "muito",
      "tempo",
      "aqui",
      "consultar",
      "antes",
      "honda",
      "2009",
      "fipe",
      "39.000",
      "valor",
      "25.000",
      "❌tem",
      "dok❌",
      "detalhado",
      "vídeo",
      "higienizar",
      "interna",
      "gela",
      "para",
      "brisa"
    ]
  },
  {
    "id": "DV0qgeXAGvH",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "REPASSE AUTOPAR",
    "description": "REPASSE AUTOPAR\n\nSandero\n\nAno 2021\n\n1.0 zen\n\nCompleto ar gelando\n\nFipe 48.000\n\nValor 38.000\n\nSem leilão\n\nSem sinistro\n\nPneus meia vida bom\n\nLataria detalhe pára-choque traseiro\n\nE martelo pára-lama passageiro\n\nHigienizar a interna",
    "price": "Consulte",
    "image": "",
    "url": "https://www.instagram.com/p/DV0qgeXAGvH/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "repasse",
      "autopar",
      "sandero",
      "2021",
      "completo",
      "gelando",
      "fipe",
      "48.000",
      "valor",
      "38.000",
      "leilão",
      "sinistro",
      "pneus",
      "meia",
      "vida",
      "lataria",
      "detalhe",
      "pára-choque",
      "traseiro",
      "martelo",
      "pára-lama",
      "passageiro",
      "higienizar",
      "interna"
    ]
  },
  {
    "id": "DVqPdbAgA4b",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "✅ AUTOPAR REPASSES",
    "description": "✅ AUTOPAR REPASSES\n\nNÃO SERÁ LIBERADO A RETIRADA DO CARRO SEM O COMUNICADO DE VENDAS\n(Não concedemos prazo pra transferência)\n\nEndereço do pátio\n📍 Rua Omilio Monteiro Soares, 1686 – Fanny – Curitiba/PR\n\nMARCA: FIAT\nMODELO: ARGO flex\n🚙 VERSÃO: 1.0\nANO 2024/2025\nKm 50 mil\n\n✅ SEM SINISTRO\n✅SEM LEILÃO\n✅ CAUTELAR\n\n📊 FIPE: R$72.200\n\nR$13.200 a baixo da Fipe\n\n💰 Repasse: R$59.000\n\nVenda fora do estado acr",
    "price": "R$72.200",
    "image": "imagens/autopar.repasses_DVqPdbAgA4b.jpg",
    "url": "https://www.instagram.com/p/DVqPdbAgA4b/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "será",
      "liberado",
      "retirada",
      "carro",
      "comunicado",
      "vendas",
      "(não",
      "concedemos",
      "prazo",
      "transferência)",
      "endereço",
      "pátio",
      "omilio",
      "monteiro",
      "soares,",
      "1686",
      "fanny",
      "curitiba/pr",
      "marca:",
      "fiat",
      "modelo:",
      "argo",
      "flex"
    ]
  },
  {
    "id": "DUg1zF5EZga",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nREPASSES\n\nAutopar Repasses\n\nTracker 1.0 turbo LT\n2024/2025\nCompleta\nMultimídia\nPericiada 100% ( sem retoque )\nPneus bons\nKm 82.000 ( ate 80 na css)\nGarantia de fabrica\nManual, nota fiscal e chave copia\nFipe 111.000\nPreciso de 89.000\nIPVA 2026 QUITADO\n\nRua OMILIO MONTEIRO SOARES 1686 Fanny Curitiba pr",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DUg1zF5EZga.jpg",
    "url": "https://www.instagram.com/p/DUg1zF5EZga/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "repasses",
      "autopar",
      "repasses",
      "tracker",
      "turbo",
      "2024/2025",
      "completa",
      "multimídia",
      "periciada",
      "100%",
      "retoque",
      "pneus",
      "bons",
      "82.000",
      "css)",
      "garantia",
      "fabrica",
      "manual,",
      "nota",
      "fiscal",
      "chave",
      "copia",
      "fipe",
      "111.000"
    ]
  },
  {
    "id": "DVqD9jpjqFU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Repasses AUTOPAR",
    "description": "Repasses AUTOPAR\n\nVendido com vantagem comercial\n\nFIAT UNO FIRE\n4 portas\nKm130 mil\nAno 2016\nBásico\n\nFazer\nTransferência\nPára-choque dianteiro\nDocumento em dia\n\nSem leilão sem sinistro\n\nFipe33.500\n\nRepasse por R$22.000 mil",
    "price": "R$22.000",
    "image": "imagens/autopar.repasses_DVqD9jpjqFU.jpg",
    "url": "https://www.instagram.com/p/DVqD9jpjqFU/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "repasses",
      "autopar",
      "vendido",
      "vantagem",
      "comercial",
      "fiat",
      "fire",
      "portas",
      "km130",
      "2016",
      "básico",
      "fazer",
      "transferência",
      "pára-choque",
      "dianteiro",
      "documento",
      "leilão",
      "sinistro",
      "fipe33.500",
      "repasse",
      "r$22.000"
    ]
  },
  {
    "id": "DVWC59_gPTZ",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nAUTOPAR REPASSES\n\nCitroen C3 ATTRACTIVE\nKM 220 mil\n\nÚnico dono\n\nCarro sem defeitos\n\nFipe\nR$54.500\nPor R$42.000",
    "price": "R$54.500",
    "image": "imagens/autopar.repasses_DVWC59_gPTZ.jpg",
    "url": "https://www.instagram.com/p/DVWC59_gPTZ/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "autopar",
      "repasses",
      "citroen",
      "attractive",
      "único",
      "dono",
      "carro",
      "defeitos",
      "fipe",
      "r$54.500",
      "r$42.000"
    ]
  },
  {
    "id": "DNwcIC_wMhW",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Senhores",
    "description": "Senhores\n\n——————————-\n\nTemos pátio para melhor\nAtendimento\n\n——————————-\nLojista, investidor e iniciantes\nSEJA BEM VINDOS\n\nRua OMILIO MONTEIRO SOARES\n1686 Fanny Curitiba Paraná\n\n(41)9.9104-4503\nJociel\n(41)9.9104-4302\nRoniel",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DNwcIC_wMhW.jpg",
    "url": "https://www.instagram.com/p/DNwcIC_wMhW/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "senhores",
      "——————————-",
      "temos",
      "pátio",
      "para",
      "melhor",
      "atendimento",
      "——————————-",
      "lojista,",
      "investidor",
      "iniciantes",
      "seja",
      "vindos",
      "omilio",
      "monteiro",
      "soares",
      "1686",
      "fanny",
      "curitiba",
      "paraná",
      "(41)9.9104-4503",
      "jociel",
      "(41)9.9104-4302",
      "roniel"
    ]
  },
  {
    "id": "DUg2iB3kYhX",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Repasse",
    "description": "Repasse\n\nX Sara Picasso\n1.6 mec\n2007\nKM 180 mil\n\nAr não gelou\nPra andar é boa\nPneus bons\nMotor funcionando\nClaro que tem 19 anos de uso\n\nFipe\nR$15.000\nPor 10 mil mais despesas",
    "price": "R$15.000",
    "image": "imagens/autopar.repasses_DUg2iB3kYhX.jpg",
    "url": "https://www.instagram.com/p/DUg2iB3kYhX/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "repasse",
      "sara",
      "picasso",
      "2007",
      "gelou",
      "andar",
      "pneus",
      "bons",
      "motor",
      "funcionando",
      "claro",
      "anos",
      "fipe",
      "r$15.000",
      "mais",
      "despesas"
    ]
  },
  {
    "id": "DVqMaaWABUc",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Ecosport 2.0 4wd freestyle",
    "description": "Ecosport 2.0 4wd freestyle\nAno 2017\nAnual\n\nCompleto\nAr condicionado gela\nSuspensão boa\nCouro\n5 pneus bons\nMídia\n\nFazer\nTransferência\n4 peças\n\nFipe\nR$64.500\nPor R$53.000",
    "price": "R$64.500",
    "image": "imagens/autopar.repasses_DVqMaaWABUc.jpg",
    "url": "https://www.instagram.com/p/DVqMaaWABUc/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "ecosport",
      "freestyle",
      "2017",
      "anual",
      "completo",
      "condicionado",
      "gela",
      "suspensão",
      "couro",
      "pneus",
      "bons",
      "mídia",
      "fazer",
      "transferência",
      "peças",
      "fipe",
      "r$64.500",
      "r$53.000"
    ]
  },
  {
    "id": "DVAtEqsAOXU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Ka hatch 1.0 2021",
    "description": "Ka hatch 1.0 2021\nCompleto\nAr trincando\nPneus bons\nCarro com muita qualidade\nZero de mecânica\nKm 80.000\nGastos do retoque parachoque traseiro\nFipe 50.500\n\nPreciso de 43.500\n\nTRANSFERÊNCIA IMEDIATA DE PRODUTIVIDADE",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVAtEqsAOXU.jpg",
    "url": "https://www.instagram.com/p/DVAtEqsAOXU/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "hatch",
      "2021",
      "completo",
      "trincando",
      "pneus",
      "bons",
      "carro",
      "muita",
      "qualidade",
      "zero",
      "mecânica",
      "80.000",
      "gastos",
      "retoque",
      "parachoque",
      "traseiro",
      "fipe",
      "50.500",
      "preciso",
      "43.500",
      "transferência",
      "imediata",
      "produtividade"
    ]
  },
  {
    "id": "DVqNEsqAIEE",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "AUTOPAR REPASSES",
    "description": "AUTOPAR REPASSES\n\nFIAT TORO FREEDON\n2.4 flex\nKm 150 mil\n\nLataria ótima\nInterna Ótima\nSuspensão ótima\nBoa pra andar\n\nPneus ruins\n\nTransferência obrigatória\n\nDoc em dia\n\nR$82.700\n\nR$68.000",
    "price": "R$82.700",
    "image": "imagens/autopar.repasses_DVqNEsqAIEE.jpg",
    "url": "https://www.instagram.com/p/DVqNEsqAIEE/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "fiat",
      "toro",
      "freedon",
      "flex",
      "lataria",
      "ótima",
      "interna",
      "ótima",
      "suspensão",
      "ótima",
      "andar",
      "pneus",
      "ruins",
      "transferência",
      "obrigatória",
      "r$82.700",
      "r$68.000"
    ]
  },
  {
    "id": "DV5s1_lAGvx",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "REPASSE AUTOPAR",
    "description": "REPASSE AUTOPAR\n\nBMW\n125i M Sport/Active Flex 2.0 TB\nAut. 5p\n\n2014 Gasolina\n\nFipe R$ 109.228,00\n\nPor R$91.000\n\nSem leilão sem sinistro",
    "price": "R$ 109.228,00",
    "image": "imagens/autopar.repasses_DV5s1_lAGvx.jpg",
    "url": "https://www.instagram.com/p/DV5s1_lAGvx/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "repasse",
      "autopar",
      "125i",
      "sport/active",
      "flex",
      "aut.",
      "2014",
      "gasolina",
      "fipe",
      "109.228,00",
      "r$91.000",
      "leilão",
      "sinistro"
    ]
  },
  {
    "id": "DVAtUKPAEi6",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nRENALT DUSTER\nDYNAMIC 2013/2013\nKm160k\n\nSem leilão sem sinistro\n\nFipe\nR$46.500\nPor R$30.000\n\nMargem R$16.500",
    "price": "R$46.500",
    "image": "imagens/autopar.repasses_DVAtUKPAEi6.jpg",
    "url": "https://www.instagram.com/p/DVAtUKPAEi6/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "renalt",
      "duster",
      "dynamic",
      "2013/2013",
      "km160k",
      "leilão",
      "sinistro",
      "fipe",
      "r$46.500",
      "r$30.000",
      "margem",
      "r$16.500"
    ]
  },
  {
    "id": "DRbxJ56gM2p",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "AUTOPAR REPASSES",
    "description": "AUTOPAR REPASSES\n\nNosso trabalho\n\nRepassar veículos por ano modelo e versão a qual nossos fornecedores não querem em seu estoque, viabilizando a venda e a dissolução de veículos no mercado",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DRbxJ56gM2p.jpg",
    "url": "https://www.instagram.com/p/DRbxJ56gM2p/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "nosso",
      "trabalho",
      "repassar",
      "veículos",
      "modelo",
      "versão",
      "qual",
      "nossos",
      "fornecedores",
      "querem",
      "estoque,",
      "viabilizando",
      "venda",
      "dissolução",
      "veículos",
      "mercado"
    ]
  },
  {
    "id": "DVkucgUl4VF",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Repasse AUTOPAR",
    "description": "Repasse AUTOPAR\n\nKIA Picanto EX3 2.0l\nAno 2011\nCompleto\nAr não gela\nPneus novos\nKm 146\nFipe 28.530\n\nR$23.500",
    "price": "R$23.500",
    "image": "imagens/autopar.repasses_DVkucgUl4VF.jpg",
    "url": "https://www.instagram.com/p/DVkucgUl4VF/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "repasse",
      "autopar",
      "picanto",
      "2.0l",
      "2011",
      "completo",
      "gela",
      "pneus",
      "novos",
      "fipe",
      "28.530",
      "r$23.500"
    ]
  },
  {
    "id": "story_autopar.repasses_1773864797",
    "tipo": "story",
    "store": "@autopar.repasses",
    "title": "Story de @autopar.repasses",
    "description": "Story capturado em 18/03/2026 17:13 — dura 24h.",
    "price": "Consulte",
    "image": "imagens/story_autopar.repasses_0_1773864797.jpg",
    "url": "https://www.instagram.com/autopar.repasses/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "story",
      "autopar.repasses"
    ]
  },
  {
    "id": "DSpVEx1jbOK",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "Feliz Natal e Ano Novo a Todos! 🙏🏻",
    "description": "Feliz Natal e Ano Novo a Todos! 🙏🏻",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DSpVEx1jbOK.jpg",
    "url": "https://www.instagram.com/p/DSpVEx1jbOK/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "feliz",
      "natal",
      "novo",
      "todos!"
    ]
  },
  {
    "id": "DF34LwVPCRt",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "MERCEDES A35 AMG TB 2020🔥",
    "description": "MERCEDES A35 AMG TB 2020🔥\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Revisões na Concessionária\n• ⁠Manual e Chave Reserva\n• ⁠Veículo está Impecável\n• ⁠Interna Alcântara\n• ⁠IPVA 25 em Dia\n• ⁠4 Pneus Bons\n• ⁠Painel Digital\n• ⁠65 MIL KM\n• ⁠Teto Solar\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 284.000,00\nVALOR$ 244.000💰\n\n40 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 244.000",
    "image": "imagens/cwb.repasse__DF34LwVPCRt.jpg",
    "url": "https://www.instagram.com/p/DF34LwVPCRt/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "mercedes",
      "2020🔥",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "revisões",
      "concessionária",
      "⁠manual",
      "chave",
      "reserva",
      "⁠veículo",
      "está",
      "impecável",
      "⁠interna",
      "alcântara",
      "⁠ipva",
      "pneus",
      "bons",
      "⁠painel",
      "digital",
      "⁠teto",
      "solar",
      "consta",
      "leilão",
      "fipe:",
      "284.000,00",
      "valor$"
    ]
  },
  {
    "id": "DDmUObMR3O_",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "VW GOLF GTI 2015 VENDIDO ✔️",
    "description": "VW GOLF GTI 2015 VENDIDO ✔️\n\nParabéns Gustavo pela conquista! Excelente escolha.\n\nEsse foi para PIRAI DO SUL - PR📍\n\n#seminovos #bomnegocio #carroscuritiba #volkswagen #golfgti #stage2 #performance #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DDmUObMR3O_.jpg",
    "url": "https://www.instagram.com/p/DDmUObMR3O_/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "2015",
      "vendido",
      "parabéns",
      "gustavo",
      "pela",
      "conquista!",
      "excelente",
      "escolha.",
      "esse",
      "para",
      "pirai",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagen",
      "golfgti",
      "stage2",
      "performance",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DBv1-D4JjMV",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GM ONIX LT 2023 VENDIDO ✔️",
    "description": "GM ONIX LT 2023 VENDIDO ✔️\n\nEsse foi para nosso amigo e cliente Rodrigo! Obrigado pela preferência e Confiança irmão 👊🏻\n\n#seminovos #bomnegocio #carroscuritiba #chevrolet #onixplus #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 998932889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DBv1-D4JjMV.jpg",
    "url": "https://www.instagram.com/p/DBv1-D4JjMV/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "onix",
      "2023",
      "vendido",
      "esse",
      "para",
      "nosso",
      "amigo",
      "cliente",
      "rodrigo!",
      "obrigado",
      "pela",
      "preferência",
      "confiança",
      "irmão",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "chevrolet",
      "onixplus",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "998932889"
    ]
  },
  {
    "id": "DGap3pZRmSw",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "RANGER LIMITED 2019 VENDIDO ✔️",
    "description": "RANGER LIMITED 2019 VENDIDO ✔️\n\nParabéns Fábio pela conquista! Linda caminhonete, fez uma ótima escolha.\n\nEssa vai para Santa Catarina📍\n\n#seminovos #bomnegocio #carroscuritiba #fordranger #caminhonete #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DGap3pZRmSw.jpg",
    "url": "https://www.instagram.com/p/DGap3pZRmSw/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "ranger",
      "limited",
      "2019",
      "vendido",
      "parabéns",
      "fábio",
      "pela",
      "conquista!",
      "linda",
      "caminhonete,",
      "ótima",
      "escolha.",
      "essa",
      "para",
      "santa",
      "catarina📍",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "fordranger",
      "caminhonete",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)"
    ]
  },
  {
    "id": "DJ5L1JvvNB4",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "NIVUS HIGHLINE 200 TSI 2021",
    "description": "NIVUS HIGHLINE 200 TSI 2021\n\n• Revisões na Concessionária até 85km\n• Manual e Chave Reserva\n• ⁠Veículo de Único Dono\n• ⁠P/ Pessoas Exigentes\n• ⁠IPVA 25 Quitado\n• ⁠4 Pneus Bons\n• ⁠96 MIL KM\n• ⁠Painel TFT\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 106.400,00\nVALOR$ 94.500💰\n\n12 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 94.500",
    "image": "imagens/cwb.repasse__DJ5L1JvvNB4.jpg",
    "url": "https://www.instagram.com/p/DJ5L1JvvNB4/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "nivus",
      "highline",
      "2021",
      "revisões",
      "concessionária",
      "85km",
      "manual",
      "chave",
      "reserva",
      "⁠veículo",
      "único",
      "dono",
      "pessoas",
      "exigentes",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠painel",
      "consta",
      "leilão",
      "fipe:",
      "106.400,00",
      "valor$",
      "94.500💰"
    ]
  },
  {
    "id": "DP5LXUwDfb9",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "HONDA CIVIC 2.0 EXL AUT. 2020",
    "description": "HONDA CIVIC 2.0 EXL AUT. 2020\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Pericia Cautelar Aprovada\n• ⁠Revisões Todas em Dia\n• ⁠Veículo está Impecável\n• ⁠Interna Couro Ótima\n• ⁠IPVA 25 Quitado\n• ⁠4 Pneus Bons\n• ⁠128 MIL KM\n• ⁠Multimídia\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 121.000,00\nVALOR$ 109.000💰\n\n12 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 109.000",
    "image": "imagens/cwb.repasse__DP5LXUwDfb9.jpg",
    "url": "https://www.instagram.com/p/DP5LXUwDfb9/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "honda",
      "civic",
      "aut.",
      "2020",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "pericia",
      "cautelar",
      "aprovada",
      "⁠revisões",
      "todas",
      "⁠veículo",
      "está",
      "impecável",
      "⁠interna",
      "couro",
      "ótima",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠128",
      "⁠multimídia",
      "consta",
      "leilão",
      "fipe:"
    ]
  },
  {
    "id": "C-sIa_wJ0Sq",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "CRUZE LTZ 2017 EMBARCANDO ✈️",
    "description": "CRUZE LTZ 2017 EMBARCANDO ✈️\n\n• Esse vai para o Rio Grande do Sul - RS📍\n\n#seminovos #bomnegocio #carroscuritiba #chevrolet #cruzeturbo #abaixodafipe #cwbrepasse #vemvctbm\n\nMais informações:\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__C-sIa_wJ0Sq.jpg",
    "url": "https://www.instagram.com/p/C-sIa_wJ0Sq/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "cruze",
      "2017",
      "embarcando",
      "esse",
      "para",
      "grande",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "chevrolet",
      "cruzeturbo",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "mais",
      "informações:",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DAms9RuPbpi",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "BMW 328i SPORT 2.0 AUT. 2015",
    "description": "BMW 328i SPORT 2.0 AUT. 2015\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• ⁠Revisões Recém Feitas\n• ⁠Manual do Proprietário\n• ⁠Veículo Inteiro no PPF\n• ⁠Interna Couro Ótima\n• ⁠IPVA 24 Quitado\n• ⁠2 Pneus Bons\n• ⁠90 MIL KM\n• ⁠Multimídia\n• ⁠Blindada\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 122.000,00\nVALOR$ 97.500💰\n\n25 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 97.500",
    "image": "imagens/cwb.repasse__DAms9RuPbpi.jpg",
    "url": "https://www.instagram.com/p/DAms9RuPbpi/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "328i",
      "sport",
      "aut.",
      "2015",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "⁠revisões",
      "recém",
      "feitas",
      "⁠manual",
      "proprietário",
      "⁠veículo",
      "inteiro",
      "⁠interna",
      "couro",
      "ótima",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠multimídia",
      "⁠blindada",
      "consta",
      "leilão",
      "fipe:",
      "122.000,00"
    ]
  },
  {
    "id": "DCJ4SdAv60I",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "VOLVO XC60 HÍBRIDA VENDIDA ✈️",
    "description": "VOLVO XC60 HÍBRIDA VENDIDA ✈️\n\nEssa foi para nosso amigo e cliente Rafael! Obrigado irmão pela confiança 👊🏻\n\n#seminovos #bomnegocio #carroscuritiba #premium #volvoxc60 #hibrido #abaixodafipe #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DCJ4SdAv60I.jpg",
    "url": "https://www.instagram.com/p/DCJ4SdAv60I/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "volvo",
      "xc60",
      "híbrida",
      "vendida",
      "essa",
      "para",
      "nosso",
      "amigo",
      "cliente",
      "rafael!",
      "obrigado",
      "irmão",
      "pela",
      "confiança",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "premium",
      "volvoxc60",
      "hibrido",
      "abaixodafipe",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DCE8e25vd0U",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "VW NIVUS TSI 2021 VENDIDO ✔️",
    "description": "VW NIVUS TSI 2021 VENDIDO ✔️\n\nMais uma nave entregue!\nEsse foi para Santa Catarina📍\n\n#seminovos #bomnegocio #carroscuritiba #volkswagen #nivushighline #abaixodafipe #cwbrepasse #aprovado #vemvocêtbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DCE8e25vd0U.jpg",
    "url": "https://www.instagram.com/p/DCE8e25vd0U/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "nivus",
      "2021",
      "vendido",
      "mais",
      "nave",
      "entregue!",
      "esse",
      "para",
      "santa",
      "catarina📍",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagen",
      "nivushighline",
      "abaixodafipe",
      "cwbrepasse",
      "aprovado",
      "vemvocêtbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DGW_w4lNWqh",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "FORD RANGER CD LIMITED 2019",
    "description": "FORD RANGER CD LIMITED 2019\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• ⁠Revisões Todas em Dia\n• ⁠Possui Chave Reserva\n• ⁠Veículo sem Detalhes\n• ⁠Interna Couro Ótima\n• ⁠IPVA 24 Quitado\n• ⁠4 Pneus Bons\n• ⁠128 MIL KM\n• ⁠Multimídia\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 150.000,00\nVALOR$ 125.000💰\n\n25 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 125.000",
    "image": "imagens/cwb.repasse__DGW_w4lNWqh.jpg",
    "url": "https://www.instagram.com/p/DGW_w4lNWqh/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "ford",
      "ranger",
      "limited",
      "2019",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "⁠revisões",
      "todas",
      "⁠possui",
      "chave",
      "reserva",
      "⁠veículo",
      "detalhes",
      "⁠interna",
      "couro",
      "ótima",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠128",
      "⁠multimídia",
      "consta",
      "leilão",
      "fipe:",
      "150.000,00"
    ]
  },
  {
    "id": "DOBOJ3VDaz6",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "COROLLA XEI 2024 VENDIDO ✔️",
    "description": "COROLLA XEI 2024 VENDIDO ✔️\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\nParabéns José pela conquista! Excelente escolha.\n\n#seminovos #bomnegocio #carroscuritiba #toyota #corollaxei #executivo #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DOBOJ3VDaz6.jpg",
    "url": "https://www.instagram.com/p/DOBOJ3VDaz6/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "corolla",
      "2024",
      "vendido",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "parabéns",
      "josé",
      "pela",
      "conquista!",
      "excelente",
      "escolha.",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "toyota",
      "corollaxei",
      "executivo",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DVegqvZAQnm",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "VW TIGUAN R-LINE 2019 VENDIDA ✔️",
    "description": "VW TIGUAN R-LINE 2019 VENDIDA ✔️\n\nEssa foi para Jaraguá do Sul - SC📍\n\nParabéns Gustavo pela conquista! Excelente escolha!\n\n#seminovos #bomnegocio #carroscuritiba #volkwagen #tiguanrline vem vc tbm.\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DVegqvZAQnm.jpg",
    "url": "https://www.instagram.com/p/DVegqvZAQnm/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "tiguan",
      "r-line",
      "2019",
      "vendida",
      "essa",
      "para",
      "jaraguá",
      "parabéns",
      "gustavo",
      "pela",
      "conquista!",
      "excelente",
      "escolha!",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkwagen",
      "tiguanrline",
      "tbm.",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DAL6Ab4Ptro",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GOLF TSI 2018 VENDIDO ✔️",
    "description": "GOLF TSI 2018 VENDIDO ✔️\n\nMais uma nave entregue! Parabéns Cleison pela excelente escolha.\n\n#seminovos #bomnegocio #carroscuritiba #volkswagen #performance #golftsi #turbo #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DAL6Ab4Ptro.jpg",
    "url": "https://www.instagram.com/p/DAL6Ab4Ptro/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "2018",
      "vendido",
      "mais",
      "nave",
      "entregue!",
      "parabéns",
      "cleison",
      "pela",
      "excelente",
      "escolha.",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagen",
      "performance",
      "golftsi",
      "turbo",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DQJqFQxjaoZ",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "🐎 MERCEDES C-250 SPORT 2.0 TURBO COUPÉ 2017",
    "description": "🐎 MERCEDES C-250 SPORT 2.0 TURBO COUPÉ 2017\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Pericia Cautelar Aprovada\n• ⁠Manual e Chave Reserva\n• ⁠Revisões Recém Feitas\n• ⁠Interna Couro Ótima\n• ⁠Apenas Polimento\n• ⁠IPVA 25 Quitado\n• ⁠4 Pneus Bons\n• ⁠App Car Play\n• ⁠99 MIL KM\n• ⁠Teto Solar\n• ⁠KIT AMG\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 187.000,00\nVALOR$ 147.000💰\n\n40 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 147.000",
    "image": "imagens/cwb.repasse__DQJqFQxjaoZ.jpg",
    "url": "https://www.instagram.com/p/DQJqFQxjaoZ/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "mercedes",
      "c-250",
      "sport",
      "turbo",
      "coupé",
      "2017",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "pericia",
      "cautelar",
      "aprovada",
      "⁠manual",
      "chave",
      "reserva",
      "⁠revisões",
      "recém",
      "feitas",
      "⁠interna",
      "couro",
      "ótima",
      "⁠apenas",
      "polimento",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons"
    ]
  },
  {
    "id": "DGjPoMIP5si",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "COROLLA HÍBRIDO 2022 VENDIDO ✔️",
    "description": "COROLLA HÍBRIDO 2022 VENDIDO ✔️\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\nParabéns Daniel pela conquista! Agradecemos a preferência e confiança.\n\nDeus te abençoe com essa máquina 🙏🏻\n\n.\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DGjPoMIP5si.jpg",
    "url": "https://www.instagram.com/p/DGjPoMIP5si/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "corolla",
      "híbrido",
      "2022",
      "vendido",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "parabéns",
      "daniel",
      "pela",
      "conquista!",
      "agradecemos",
      "preferência",
      "confiança.",
      "deus",
      "abençoe",
      "essa",
      "máquina",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DOdv3OGjSFR",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "BMW X1 SPORT 2019 VENDIDA ✔️",
    "description": "BMW X1 SPORT 2019 VENDIDA ✔️\n\n🏅Parabéns Marcinho! Excelente escolha.\n\nAgradecemos a preferência e confiança em nosso trabalho.\n\n#seminovospremium #bomnegocio #carroscuritiba #sportmotivation #bmw #cwbrepasse #vemvctambém\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DOdv3OGjSFR.jpg",
    "url": "https://www.instagram.com/p/DOdv3OGjSFR/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "sport",
      "2019",
      "vendida",
      "🏅parabéns",
      "marcinho!",
      "excelente",
      "escolha.",
      "agradecemos",
      "preferência",
      "confiança",
      "nosso",
      "trabalho.",
      "seminovospremium",
      "bomnegocio",
      "carroscuritiba",
      "sportmotivation",
      "bmw",
      "cwbrepasse",
      "vemvctambém",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DRmgmxtjTvj",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "Hoje fomos recebidos em uma das melhores lojas aqui de Curitiba! …",
    "description": "Hoje fomos recebidos em uma das melhores lojas aqui de Curitiba! 🏎️ @viasohomotors\n\nApenas agradecer pela parceria e atendimento 👊🏼",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DRmgmxtjTvj.jpg",
    "url": "https://www.instagram.com/p/DRmgmxtjTvj/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "hoje",
      "fomos",
      "recebidos",
      "melhores",
      "lojas",
      "aqui",
      "curitiba!",
      "viasohomotors",
      "apenas",
      "agradecer",
      "pela",
      "parceria",
      "atendimento"
    ]
  },
  {
    "id": "DDsdfdRv9Xm",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "TIGUAN TSI 2015 VENDIDA ✔️",
    "description": "TIGUAN TSI 2015 VENDIDA ✔️\n\nParabéns ao casal Wagner e Gabrieli pela excelente escolha!\n\nAgradecemos a preferência e confiança 🙏🏻\n\n#seminovos #bomnegocio #carroscuritiba #volkswagen #tiguantsi #abaixodafipe #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DDsdfdRv9Xm.jpg",
    "url": "https://www.instagram.com/p/DDsdfdRv9Xm/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "tiguan",
      "2015",
      "vendida",
      "parabéns",
      "casal",
      "wagner",
      "gabrieli",
      "pela",
      "excelente",
      "escolha!",
      "agradecemos",
      "preferência",
      "confiança",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagen",
      "tiguantsi",
      "abaixodafipe",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DPXEtm4EonQ",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GOLF VARIANT HIGHLINE 1.4 TSI 2015",
    "description": "GOLF VARIANT HIGHLINE 1.4 TSI 2015\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Manual e Chave Reserva\n• Revisões Recém Feitas\n• ⁠Interna Couro Ótima\n• ⁠Veículo Impecável\n• ⁠IPVA 25 Quitado\n• ⁠4 Pneus Bons\n• ⁠102 MIL KM\n• ⁠Multimídia\n• ⁠Teto Solar\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: ⁠82.000,00\nVALOR$ 72.000💰\n\n• Aceitamos carro de entrada!\n\nCURITIBA📍",
    "price": "R$ 72.000",
    "image": "imagens/cwb.repasse__DPXEtm4EonQ.jpg",
    "url": "https://www.instagram.com/p/DPXEtm4EonQ/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "variant",
      "highline",
      "2015",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "manual",
      "chave",
      "reserva",
      "revisões",
      "recém",
      "feitas",
      "⁠interna",
      "couro",
      "ótima",
      "⁠veículo",
      "impecável",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠102",
      "⁠multimídia",
      "⁠teto",
      "solar",
      "consta"
    ]
  },
  {
    "id": "DNa1VUWturT",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "POLO SEDAN 1.6 2012 VENDIDO ✔️",
    "description": "POLO SEDAN 1.6 2012 VENDIDO ✔️\n\n• Agradecemos a preferência e confiança Felipe!\n\n#seminovos #bomnegocio #carroscuritiba #volkswagem #polosedan #abaixodafipe #vemvctambém\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DNa1VUWturT.jpg",
    "url": "https://www.instagram.com/p/DNa1VUWturT/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "polo",
      "sedan",
      "2012",
      "vendido",
      "agradecemos",
      "preferência",
      "confiança",
      "felipe!",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagem",
      "polosedan",
      "abaixodafipe",
      "vemvctambém",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "C-wUjo6tJhR",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "ONIX TURBO & 308 VENDIDOS ✈️",
    "description": "ONIX TURBO & 308 VENDIDOS ✈️\n\nPrimeiramente agradecer a Deus!\nE também a confiança dos home em nosso trabalho.\n\nDestino: CASCAVEL - PR📍\n\n#seminovos #bomnegocio #carroscuritiba #onixturbo #308turbo #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__C-wUjo6tJhR.jpg",
    "url": "https://www.instagram.com/p/C-wUjo6tJhR/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "onix",
      "turbo",
      "vendidos",
      "primeiramente",
      "agradecer",
      "deus!",
      "também",
      "confiança",
      "home",
      "nosso",
      "trabalho.",
      "destino:",
      "cascavel",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "onixturbo",
      "308turbo",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "C-yGKnDPVgN",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "HB20S TURBO 2020 VENDIDO ✔️",
    "description": "HB20S TURBO 2020 VENDIDO ✔️\n\nPra fechar essa semana abençoada.\n\nMais uma venda concluída! 🙏🏻\n\n#seminovos #bomnegocio #carroscuritiba #hyundai\n#hb20sedan #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__C-yGKnDPVgN.jpg",
    "url": "https://www.instagram.com/p/C-yGKnDPVgN/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "hb20s",
      "turbo",
      "2020",
      "vendido",
      "fechar",
      "essa",
      "semana",
      "abençoada.",
      "mais",
      "venda",
      "concluída!",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "hyundai",
      "hb20sedan",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DD-XpfSPE_h",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "Desejamos a todos nossos amigos e Clientes um Feliz Natal. Com mu…",
    "description": "Desejamos a todos nossos amigos e Clientes um Feliz Natal. Com muita saúde e paz 🙏🏻🎅🏻\n\n@cwb.repasse_",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DD-XpfSPE_h.jpg",
    "url": "https://www.instagram.com/p/DD-XpfSPE_h/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "desejamos",
      "todos",
      "nossos",
      "amigos",
      "clientes",
      "feliz",
      "natal.",
      "muita",
      "saúde",
      "🙏🏻🎅🏻",
      "cwb.repasse_"
    ]
  },
  {
    "id": "DQR3lrYDXg-",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "🐎 JETTA R-LINE 2018 VENDIDO ✔️",
    "description": "🐎 JETTA R-LINE 2018 VENDIDO ✔️\n\nExcelente escolha Wesley! Deus te abençoe com essa nova conquista 👊🏻\n\n#seminovos #carroscuritiba #veiculospremium #esportivos #volkswagem #jettatsi #cwbrepasse #abaixodafipe #menorpreço #vemvctbém\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DQR3lrYDXg-.jpg",
    "url": "https://www.instagram.com/p/DQR3lrYDXg-/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "jetta",
      "r-line",
      "2018",
      "vendido",
      "excelente",
      "escolha",
      "wesley!",
      "deus",
      "abençoe",
      "essa",
      "nova",
      "conquista",
      "seminovos",
      "carroscuritiba",
      "veiculospremium",
      "esportivos",
      "volkswagem",
      "jettatsi",
      "cwbrepasse",
      "abaixodafipe",
      "menorpreço",
      "vemvctbém",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "C_d7UXAPqzb",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "NISSAN LEAF 2022 VENDIDO ✈️",
    "description": "NISSAN LEAF 2022 VENDIDO ✈️\n\nRealmente a tecnologia chegou! Parabéns Moisés pela excelente aquisição.\n\nMais um veículo 100% elétrico.\n\nEsse foi para Florianópolis - SC📍\n\n#seminovos #bomnegocio #carroscuritiba #nissan #elétrico #abaixofipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__C_d7UXAPqzb.jpg",
    "url": "https://www.instagram.com/p/C_d7UXAPqzb/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "nissan",
      "leaf",
      "2022",
      "vendido",
      "realmente",
      "tecnologia",
      "chegou!",
      "parabéns",
      "moisés",
      "pela",
      "excelente",
      "aquisição.",
      "mais",
      "veículo",
      "100%",
      "elétrico.",
      "esse",
      "para",
      "florianópolis",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "nissan",
      "elétrico",
      "abaixofipe"
    ]
  },
  {
    "id": "DBro7BQvsyG",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GOLF TSI 2018 VENDIDO ✔️",
    "description": "GOLF TSI 2018 VENDIDO ✔️\n\nParabéns Wellington pela conquista! Agradecemos a preferência e confiança.\n\nEsse ficou aqui em Curitiba📍\n\n#seminovos #bomnegocio #carroscuritiba #procedencia #volkswagen #golftsi #turbo #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DBro7BQvsyG.jpg",
    "url": "https://www.instagram.com/p/DBro7BQvsyG/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "2018",
      "vendido",
      "parabéns",
      "wellington",
      "pela",
      "conquista!",
      "agradecemos",
      "preferência",
      "confiança.",
      "esse",
      "ficou",
      "aqui",
      "curitiba📍",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "procedencia",
      "volkswagen",
      "golftsi",
      "turbo",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)"
    ]
  },
  {
    "id": "DAEac2MPTWn",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GOLF 2.0 GTI 2014 VENDIDO ✔️",
    "description": "GOLF 2.0 GTI 2014 VENDIDO ✔️\n\nEsse não deu nem tempo! Parabéns Caíque pela escolha!\n\n#seminovos #bomnegócio #carroscuritiba #volkswagen #performance #golfgti #foguete #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DAEac2MPTWn.jpg",
    "url": "https://www.instagram.com/p/DAEac2MPTWn/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "2014",
      "vendido",
      "esse",
      "tempo!",
      "parabéns",
      "caíque",
      "pela",
      "escolha!",
      "seminovos",
      "bomnegócio",
      "carroscuritiba",
      "volkswagen",
      "performance",
      "golfgti",
      "foguete",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "story_cwb.repasse__1773864984",
    "tipo": "story",
    "store": "@cwb.repasse_",
    "title": "Story de @cwb.repasse_",
    "description": "Story capturado em 18/03/2026 17:16 — dura 24h.",
    "price": "Consulte",
    "image": "imagens/story_cwb.repasse__0_1773864984.jpg",
    "url": "https://www.instagram.com/cwb.repasse_/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "story",
      "cwb.repasse_"
    ]
  },
  {
    "id": "DVjHco-DlaQ",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "Compramos seu veículo!!!",
    "description": "Compramos seu veículo!!!\n✅A melhor avaliação do mercado.\n⏱️Avaliação rápida.\n🔥Compramos seu veículo mesmo com dividas!!!\n💰Pagamento via Pix na hora.\n🔒Negociação transparente e segura.\n\nVenha fazer sua avaliação gratuita com a gente 🤝",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVjHco-DlaQ.jpg",
    "url": "https://www.instagram.com/p/DVjHco-DlaQ/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "compramos",
      "veículo!!!",
      "melhor",
      "avaliação",
      "mercado.",
      "⏱️avaliação",
      "rápida.",
      "🔥compramos",
      "veículo",
      "mesmo",
      "dividas!!!",
      "💰pagamento",
      "hora.",
      "🔒negociação",
      "transparente",
      "segura.",
      "venha",
      "fazer",
      "avaliação",
      "gratuita",
      "gente"
    ]
  },
  {
    "id": "DUS6f5GDnxR",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "RENAULT SANDERO GT LINE 1.6 2011",
    "description": "*RENAULT SANDERO GT LINE 1.6 2011*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUS6f5GDnxR.jpg",
    "url": "https://www.instagram.com/p/DUS6f5GDnxR/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*renault",
      "sandero",
      "line",
      "2011*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DVwn604jgHo",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "FORD FUSION 2.5 2016",
    "description": "*FORD FUSION 2.5 2016*\n\nVENDIDO PARA SÃO JOSÉ DOS PINHAS-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVwn604jgHo.jpg",
    "url": "https://www.instagram.com/p/DVwn604jgHo/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*ford",
      "fusion",
      "2016*",
      "vendido",
      "para",
      "josé",
      "pinhas-pr"
    ]
  },
  {
    "id": "DVi6Taujk8C",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "Você lojista ou investidor está procurando veículos abaixo da FIP…",
    "description": "Você lojista ou investidor está procurando veículos abaixo da FIPE?\nAqui você encontra novidades todos os dias!!!\nAs melhores oportunidades estão aqui, entre no nosso grupo do WhatsApp e fique por dentro 🔥",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVi6Taujk8C.jpg",
    "url": "https://www.instagram.com/p/DVi6Taujk8C/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "você",
      "lojista",
      "investidor",
      "está",
      "procurando",
      "veículos",
      "abaixo",
      "fipe?",
      "aqui",
      "você",
      "encontra",
      "novidades",
      "todos",
      "dias!!!",
      "melhores",
      "oportunidades",
      "estão",
      "aqui,",
      "entre",
      "nosso",
      "grupo",
      "whatsapp",
      "fique",
      "dentro"
    ]
  },
  {
    "id": "DUQZnurjrEN",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "PEUGEOT 208 GRIFFE 1.6 2015",
    "description": "*PEUGEOT 208 GRIFFE 1.6 2015*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUQZnurjrEN.jpg",
    "url": "https://www.instagram.com/p/DUQZnurjrEN/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*peugeot",
      "griffe",
      "2015*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DU8buNGjgJF",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "CITROËN C3 PICASSO GL 1.5 2014",
    "description": "*CITROËN C3 PICASSO GL 1.5 2014*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DU8buNGjgJF.jpg",
    "url": "https://www.instagram.com/p/DU8buNGjgJF/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*citroën",
      "picasso",
      "2014*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DUtBZYQjlIf",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "VOLKSWAGEN TIGUAN 2.0 TSI 2014",
    "description": "*VOLKSWAGEN TIGUAN 2.0 TSI 2014*\n\nVENDIDO PARA CASCAVEL-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUtBZYQjlIf.jpg",
    "url": "https://www.instagram.com/p/DUtBZYQjlIf/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*volkswagen",
      "tiguan",
      "2014*",
      "vendido",
      "para",
      "cascavel-pr"
    ]
  },
  {
    "id": "DUOLa00jr4I",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "MITSUBISHI OUTLANDER 3.0 GT AUT. 2010",
    "description": "*MITSUBISHI OUTLANDER 3.0 GT AUT. 2010*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUOLa00jr4I.jpg",
    "url": "https://www.instagram.com/p/DUOLa00jr4I/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*mitsubishi",
      "outlander",
      "aut.",
      "2010*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DUY6idnEnSW",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "HYUNDAI HB20S 1.0 FLEX 2019",
    "description": "*HYUNDAI HB20S 1.0 FLEX 2019*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUY6idnEnSW.jpg",
    "url": "https://www.instagram.com/p/DUY6idnEnSW/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*hyundai",
      "hb20s",
      "flex",
      "2019*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DUQwLSHDrCE",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "TOYOTA COROLLA XEI 1.8 2009",
    "description": "*TOYOTA COROLLA XEI 1.8 2009*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUQwLSHDrCE.jpg",
    "url": "https://www.instagram.com/p/DUQwLSHDrCE/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*toyota",
      "corolla",
      "2009*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DV_97eyjnHX",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "PEUGEOT 307 FELINE GRIFF PREMIUM 2.0 2011",
    "description": "*PEUGEOT 307 FELINE GRIFF PREMIUM 2.0 2011*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DV_97eyjnHX.jpg",
    "url": "https://www.instagram.com/p/DV_97eyjnHX/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*peugeot",
      "feline",
      "griff",
      "premium",
      "2011*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DUOJnkujkaE",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "LAND ROVER FREELANDER HSE 2.5 V6 2005",
    "description": "*LAND ROVER FREELANDER HSE 2.5 V6 2005*\n\nVENDIDO PARA SÃO PAULO-SP ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUOJnkujkaE.jpg",
    "url": "https://www.instagram.com/p/DUOJnkujkaE/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*land",
      "rover",
      "freelander",
      "2005*",
      "vendido",
      "para",
      "paulo-sp"
    ]
  },
  {
    "id": "DVt312YgVMQ",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "TOYOTA COROLLA XEi 2.0 2019",
    "description": "*TOYOTA COROLLA XEi 2.0 2019*\n\nVENDIDO PARA LONDRINA-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVt312YgVMQ.jpg",
    "url": "https://www.instagram.com/p/DVt312YgVMQ/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*toyota",
      "corolla",
      "2019*",
      "vendido",
      "para",
      "londrina-pr"
    ]
  },
  {
    "id": "DVJWSUjjkne",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "JEEP RENEGADE LONGITUDE 1.8 2017",
    "description": "*JEEP RENEGADE LONGITUDE 1.8 2017*\n\nVENDIDO PARA MARINGÁ-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVJWSUjjkne.jpg",
    "url": "https://www.instagram.com/p/DVJWSUjjkne/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*jeep",
      "renegade",
      "longitude",
      "2017*",
      "vendido",
      "para",
      "maringá-pr"
    ]
  },
  {
    "id": "DUTv8fAkq6c",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "SIENA ELX 1.0 FIRE 2007",
    "description": "*SIENA ELX 1.0 FIRE 2007*\n\nVENDIDO PARA COLOMBO-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUTv8fAkq6c.jpg",
    "url": "https://www.instagram.com/p/DUTv8fAkq6c/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "*siena",
      "fire",
      "2007*",
      "vendido",
      "para",
      "colombo-pr"
    ]
  },
  {
    "id": "story_repassesgr_1773865051",
    "tipo": "story",
    "store": "@repassesgr",
    "title": "Story de @repassesgr",
    "description": "Story capturado em 18/03/2026 17:17 — dura 24h.",
    "price": "Consulte",
    "image": "imagens/story_repassesgr_0_1773865051.jpg",
    "url": "https://www.instagram.com/repassesgr/",
    "date": "18/03/2026",
    "likes": 0,
    "keywords": [
      "story",
      "repassesgr"
    ]
  }
];
