// Atualizado: 16/03/2026 15:37
const CAR_DATA = [
  {
    "id": "DUQwLSHDrCE",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "TOYOTA COROLLA XEI 1.8 2009",
    "description": "*TOYOTA COROLLA XEI 1.8 2009*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUQwLSHDrCE.jpg",
    "url": "https://www.instagram.com/p/DUQwLSHDrCE/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*toyota",
      "corolla",
      "2009*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DVwn604jgHo",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "FORD FUSION 2.5 2016",
    "description": "*FORD FUSION 2.5 2016*\n\nVENDIDO PARA SÃO JOSÉ DOS PINHAS-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVwn604jgHo.jpg",
    "url": "https://www.instagram.com/p/DVwn604jgHo/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*ford",
      "fusion",
      "2016*",
      "vendido",
      "para",
      "josé",
      "pinhas-pr"
    ]
  },
  {
    "id": "DU8buNGjgJF",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "CITROËN C3 PICASSO GL 1.5 2014",
    "description": "*CITROËN C3 PICASSO GL 1.5 2014*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DU8buNGjgJF.jpg",
    "url": "https://www.instagram.com/p/DU8buNGjgJF/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*citroën",
      "picasso",
      "2014*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DUS6f5GDnxR",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "RENAULT SANDERO GT LINE 1.6 2011",
    "description": "*RENAULT SANDERO GT LINE 1.6 2011*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUS6f5GDnxR.jpg",
    "url": "https://www.instagram.com/p/DUS6f5GDnxR/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*renault",
      "sandero",
      "line",
      "2011*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DUTv8fAkq6c",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "SIENA ELX 1.0 FIRE 2007",
    "description": "*SIENA ELX 1.0 FIRE 2007*\n\nVENDIDO PARA COLOMBO-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUTv8fAkq6c.jpg",
    "url": "https://www.instagram.com/p/DUTv8fAkq6c/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*siena",
      "fire",
      "2007*",
      "vendido",
      "para",
      "colombo-pr"
    ]
  },
  {
    "id": "DVjHco-DlaQ",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "Compramos seu veículo!!!",
    "description": "Compramos seu veículo!!!\n✅A melhor avaliação do mercado.\n⏱️Avaliação rápida.\n🔥Compramos seu veículo mesmo com dividas!!!\n💰Pagamento via Pix na hora.\n🔒Negociação transparente e segura.\n\nVenha fazer sua avaliação gratuita com a gente 🤝",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVjHco-DlaQ.jpg",
    "url": "https://www.instagram.com/p/DVjHco-DlaQ/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "compramos",
      "veículo!!!",
      "melhor",
      "avaliação",
      "mercado.",
      "⏱️avaliação",
      "rápida.",
      "🔥compramos",
      "veículo",
      "mesmo",
      "dividas!!!",
      "💰pagamento",
      "hora.",
      "🔒negociação",
      "transparente",
      "segura.",
      "venha",
      "fazer",
      "avaliação",
      "gratuita",
      "gente"
    ]
  },
  {
    "id": "DUtBZYQjlIf",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "VOLKSWAGEN TIGUAN 2.0 TSI 2014",
    "description": "*VOLKSWAGEN TIGUAN 2.0 TSI 2014*\n\nVENDIDO PARA CASCAVEL-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUtBZYQjlIf.jpg",
    "url": "https://www.instagram.com/p/DUtBZYQjlIf/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*volkswagen",
      "tiguan",
      "2014*",
      "vendido",
      "para",
      "cascavel-pr"
    ]
  },
  {
    "id": "DUQZnurjrEN",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "PEUGEOT 208 GRIFFE 1.6 2015",
    "description": "*PEUGEOT 208 GRIFFE 1.6 2015*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUQZnurjrEN.jpg",
    "url": "https://www.instagram.com/p/DUQZnurjrEN/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*peugeot",
      "griffe",
      "2015*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DUOLa00jr4I",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "MITSUBISHI OUTLANDER 3.0 GT AUT. 2010",
    "description": "*MITSUBISHI OUTLANDER 3.0 GT AUT. 2010*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUOLa00jr4I.jpg",
    "url": "https://www.instagram.com/p/DUOLa00jr4I/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*mitsubishi",
      "outlander",
      "aut.",
      "2010*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DUOJnkujkaE",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "LAND ROVER FREELANDER HSE 2.5 V6 2005",
    "description": "*LAND ROVER FREELANDER HSE 2.5 V6 2005*\n\nVENDIDO PARA SÃO PAULO-SP ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUOJnkujkaE.jpg",
    "url": "https://www.instagram.com/p/DUOJnkujkaE/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*land",
      "rover",
      "freelander",
      "2005*",
      "vendido",
      "para",
      "paulo-sp"
    ]
  },
  {
    "id": "DVJWSUjjkne",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "JEEP RENEGADE LONGITUDE 1.8 2017",
    "description": "*JEEP RENEGADE LONGITUDE 1.8 2017*\n\nVENDIDO PARA MARINGÁ-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVJWSUjjkne.jpg",
    "url": "https://www.instagram.com/p/DVJWSUjjkne/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*jeep",
      "renegade",
      "longitude",
      "2017*",
      "vendido",
      "para",
      "maringá-pr"
    ]
  },
  {
    "id": "DVt312YgVMQ",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "TOYOTA COROLLA XEi 2.0 2019",
    "description": "*TOYOTA COROLLA XEi 2.0 2019*\n\nVENDIDO PARA LONDRINA-PR ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVt312YgVMQ.jpg",
    "url": "https://www.instagram.com/p/DVt312YgVMQ/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*toyota",
      "corolla",
      "2019*",
      "vendido",
      "para",
      "londrina-pr"
    ]
  },
  {
    "id": "DUY6idnEnSW",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "HYUNDAI HB20S 1.0 FLEX 2019",
    "description": "*HYUNDAI HB20S 1.0 FLEX 2019*\n\nVENDIDO PARA CURITIBA ✅",
    "price": "Consulte",
    "image": "imagens/repassesgr_DUY6idnEnSW.jpg",
    "url": "https://www.instagram.com/p/DUY6idnEnSW/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "*hyundai",
      "hb20s",
      "flex",
      "2019*",
      "vendido",
      "para",
      "curitiba"
    ]
  },
  {
    "id": "DVi6Taujk8C",
    "tipo": "post",
    "store": "@repassesgr",
    "title": "Você lojista ou investidor está procurando veículos abaixo da FIP…",
    "description": "Você lojista ou investidor está procurando veículos abaixo da FIPE?\nAqui você encontra novidades todos os dias!!!\nAs melhores oportunidades estão aqui, entre no nosso grupo do WhatsApp e fique por dentro 🔥",
    "price": "Consulte",
    "image": "imagens/repassesgr_DVi6Taujk8C.jpg",
    "url": "https://www.instagram.com/p/DVi6Taujk8C/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "você",
      "lojista",
      "investidor",
      "está",
      "procurando",
      "veículos",
      "abaixo",
      "fipe?",
      "aqui",
      "você",
      "encontra",
      "novidades",
      "todos",
      "dias!!!",
      "melhores",
      "oportunidades",
      "estão",
      "aqui,",
      "entre",
      "nosso",
      "grupo",
      "whatsapp",
      "fique",
      "dentro"
    ]
  },
  {
    "id": "story_repassesgr_1773685983",
    "tipo": "story",
    "store": "@repassesgr",
    "title": "Story de @repassesgr",
    "description": "Story capturado em 16/03/2026 15:33 — dura 24h.",
    "price": "Consulte",
    "image": "imagens/story_repassesgr_0_1773685983.jpg",
    "url": "https://www.instagram.com/repassesgr/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "story",
      "repassesgr"
    ]
  },
  {
    "id": "DP5LXUwDfb9",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "HONDA CIVIC 2.0 EXL AUT. 2020",
    "description": "HONDA CIVIC 2.0 EXL AUT. 2020\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Pericia Cautelar Aprovada\n• ⁠Revisões Todas em Dia\n• ⁠Veículo está Impecável\n• ⁠Interna Couro Ótima\n• ⁠IPVA 25 Quitado\n• ⁠4 Pneus Bons\n• ⁠128 MIL KM\n• ⁠Multimídia\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 121.000,00\nVALOR$ 109.000💰\n\n12 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 109.000",
    "image": "imagens/cwb.repasse__DP5LXUwDfb9.jpg",
    "url": "https://www.instagram.com/p/DP5LXUwDfb9/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "honda",
      "civic",
      "aut.",
      "2020",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "pericia",
      "cautelar",
      "aprovada",
      "⁠revisões",
      "todas",
      "⁠veículo",
      "está",
      "impecável",
      "⁠interna",
      "couro",
      "ótima",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠128",
      "⁠multimídia",
      "consta",
      "leilão",
      "fipe:"
    ]
  },
  {
    "id": "DBv1-D4JjMV",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GM ONIX LT 2023 VENDIDO ✔️",
    "description": "GM ONIX LT 2023 VENDIDO ✔️\n\nEsse foi para nosso amigo e cliente Rodrigo! Obrigado pela preferência e Confiança irmão 👊🏻\n\n#seminovos #bomnegocio #carroscuritiba #chevrolet #onixplus #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 998932889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DBv1-D4JjMV.jpg",
    "url": "https://www.instagram.com/p/DBv1-D4JjMV/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "onix",
      "2023",
      "vendido",
      "esse",
      "para",
      "nosso",
      "amigo",
      "cliente",
      "rodrigo!",
      "obrigado",
      "pela",
      "preferência",
      "confiança",
      "irmão",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "chevrolet",
      "onixplus",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "998932889"
    ]
  },
  {
    "id": "DVegqvZAQnm",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "VW TIGUAN R-LINE 2019 VENDIDA ✔️",
    "description": "VW TIGUAN R-LINE 2019 VENDIDA ✔️\n\nEssa foi para Jaraguá do Sul - SC📍\n\nParabéns Gustavo pela conquista! Excelente escolha!\n\n#seminovos #bomnegocio #carroscuritiba #volkwagen #tiguanrline vem vc tbm.\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DVegqvZAQnm.jpg",
    "url": "https://www.instagram.com/p/DVegqvZAQnm/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "tiguan",
      "r-line",
      "2019",
      "vendida",
      "essa",
      "para",
      "jaraguá",
      "parabéns",
      "gustavo",
      "pela",
      "conquista!",
      "excelente",
      "escolha!",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkwagen",
      "tiguanrline",
      "tbm.",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DJ5L1JvvNB4",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "NIVUS HIGHLINE 200 TSI 2021",
    "description": "NIVUS HIGHLINE 200 TSI 2021\n\n• Revisões na Concessionária até 85km\n• Manual e Chave Reserva\n• ⁠Veículo de Único Dono\n• ⁠P/ Pessoas Exigentes\n• ⁠IPVA 25 Quitado\n• ⁠4 Pneus Bons\n• ⁠96 MIL KM\n• ⁠Painel TFT\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 106.400,00\nVALOR$ 94.500💰\n\n12 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 94.500",
    "image": "imagens/cwb.repasse__DJ5L1JvvNB4.jpg",
    "url": "https://www.instagram.com/p/DJ5L1JvvNB4/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "nivus",
      "highline",
      "2021",
      "revisões",
      "concessionária",
      "85km",
      "manual",
      "chave",
      "reserva",
      "⁠veículo",
      "único",
      "dono",
      "pessoas",
      "exigentes",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠painel",
      "consta",
      "leilão",
      "fipe:",
      "106.400,00",
      "valor$",
      "94.500💰"
    ]
  },
  {
    "id": "DQR3lrYDXg-",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "🐎 JETTA R-LINE 2018 VENDIDO ✔️",
    "description": "🐎 JETTA R-LINE 2018 VENDIDO ✔️\n\nExcelente escolha Wesley! Deus te abençoe com essa nova conquista 👊🏻\n\n#seminovos #carroscuritiba #veiculospremium #esportivos #volkswagem #jettatsi #cwbrepasse #abaixodafipe #menorpreço #vemvctbém\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DQR3lrYDXg-.jpg",
    "url": "https://www.instagram.com/p/DQR3lrYDXg-/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "jetta",
      "r-line",
      "2018",
      "vendido",
      "excelente",
      "escolha",
      "wesley!",
      "deus",
      "abençoe",
      "essa",
      "nova",
      "conquista",
      "seminovos",
      "carroscuritiba",
      "veiculospremium",
      "esportivos",
      "volkswagem",
      "jettatsi",
      "cwbrepasse",
      "abaixodafipe",
      "menorpreço",
      "vemvctbém",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DNOrivDx6G0",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "Os melhores projetos são montados aqui na 2irmãos recuse imitaçõe…",
    "description": "Os melhores projetos são montados aqui na 2irmãos recuse imitações #rodas #pneus #sonhos #rebaiixados #polo #vwpolo",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DNOrivDx6G0.jpg",
    "url": "https://www.instagram.com/p/DNOrivDx6G0/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "melhores",
      "projetos",
      "montados",
      "aqui",
      "2irmãos",
      "recuse",
      "imitações",
      "rodas",
      "pneus",
      "sonhos",
      "rebaiixados",
      "polo",
      "vwpolo"
    ]
  },
  {
    "id": "DGjPoMIP5si",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "COROLLA HÍBRIDO 2022 VENDIDO ✔️",
    "description": "COROLLA HÍBRIDO 2022 VENDIDO ✔️\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\nParabéns Daniel pela conquista! Agradecemos a preferência e confiança.\n\nDeus te abençoe com essa máquina 🙏🏻\n\n.\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DGjPoMIP5si.jpg",
    "url": "https://www.instagram.com/p/DGjPoMIP5si/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "corolla",
      "híbrido",
      "2022",
      "vendido",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "parabéns",
      "daniel",
      "pela",
      "conquista!",
      "agradecemos",
      "preferência",
      "confiança.",
      "deus",
      "abençoe",
      "essa",
      "máquina",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DTz5qDxjfk8",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "🐎 COROLLA XEI 2024 VENDIDO ✔️",
    "description": "🐎 COROLLA XEI 2024 VENDIDO ✔️\n\nParabéns Giovane pela conquista! Excelente escolha.\n\n#seminonovos #bomnegocio #carroscuritiba #toyota #corollaxei #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DTz5qDxjfk8.jpg",
    "url": "https://www.instagram.com/p/DTz5qDxjfk8/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "corolla",
      "2024",
      "vendido",
      "parabéns",
      "giovane",
      "pela",
      "conquista!",
      "excelente",
      "escolha.",
      "seminonovos",
      "bomnegocio",
      "carroscuritiba",
      "toyota",
      "corollaxei",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DGW_w4lNWqh",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "FORD RANGER CD LIMITED 2019",
    "description": "FORD RANGER CD LIMITED 2019\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• ⁠Revisões Todas em Dia\n• ⁠Possui Chave Reserva\n• ⁠Veículo sem Detalhes\n• ⁠Interna Couro Ótima\n• ⁠IPVA 24 Quitado\n• ⁠4 Pneus Bons\n• ⁠128 MIL KM\n• ⁠Multimídia\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 150.000,00\nVALOR$ 125.000💰\n\n25 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 125.000",
    "image": "imagens/cwb.repasse__DGW_w4lNWqh.jpg",
    "url": "https://www.instagram.com/p/DGW_w4lNWqh/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "ford",
      "ranger",
      "limited",
      "2019",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "⁠revisões",
      "todas",
      "⁠possui",
      "chave",
      "reserva",
      "⁠veículo",
      "detalhes",
      "⁠interna",
      "couro",
      "ótima",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠128",
      "⁠multimídia",
      "consta",
      "leilão",
      "fipe:",
      "150.000,00"
    ]
  },
  {
    "id": "DCE8e25vd0U",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "VW NIVUS TSI 2021 VENDIDO ✔️",
    "description": "VW NIVUS TSI 2021 VENDIDO ✔️\n\nMais uma nave entregue!\nEsse foi para Santa Catarina📍\n\n#seminovos #bomnegocio #carroscuritiba #volkswagen #nivushighline #abaixodafipe #cwbrepasse #aprovado #vemvocêtbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DCE8e25vd0U.jpg",
    "url": "https://www.instagram.com/p/DCE8e25vd0U/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "nivus",
      "2021",
      "vendido",
      "mais",
      "nave",
      "entregue!",
      "esse",
      "para",
      "santa",
      "catarina📍",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagen",
      "nivushighline",
      "abaixodafipe",
      "cwbrepasse",
      "aprovado",
      "vemvocêtbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DF34LwVPCRt",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "MERCEDES A35 AMG TB 2020🔥",
    "description": "MERCEDES A35 AMG TB 2020🔥\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Revisões na Concessionária\n• ⁠Manual e Chave Reserva\n• ⁠Veículo está Impecável\n• ⁠Interna Alcântara\n• ⁠IPVA 25 em Dia\n• ⁠4 Pneus Bons\n• ⁠Painel Digital\n• ⁠65 MIL KM\n• ⁠Teto Solar\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 284.000,00\nVALOR$ 244.000💰\n\n40 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 244.000",
    "image": "imagens/cwb.repasse__DF34LwVPCRt.jpg",
    "url": "https://www.instagram.com/p/DF34LwVPCRt/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "mercedes",
      "2020🔥",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "revisões",
      "concessionária",
      "⁠manual",
      "chave",
      "reserva",
      "⁠veículo",
      "está",
      "impecável",
      "⁠interna",
      "alcântara",
      "⁠ipva",
      "pneus",
      "bons",
      "⁠painel",
      "digital",
      "⁠teto",
      "solar",
      "consta",
      "leilão",
      "fipe:",
      "284.000,00",
      "valor$"
    ]
  },
  {
    "id": "DBro7BQvsyG",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GOLF TSI 2018 VENDIDO ✔️",
    "description": "GOLF TSI 2018 VENDIDO ✔️\n\nParabéns Wellington pela conquista! Agradecemos a preferência e confiança.\n\nEsse ficou aqui em Curitiba📍\n\n#seminovos #bomnegocio #carroscuritiba #procedencia #volkswagen #golftsi #turbo #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DBro7BQvsyG.jpg",
    "url": "https://www.instagram.com/p/DBro7BQvsyG/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "2018",
      "vendido",
      "parabéns",
      "wellington",
      "pela",
      "conquista!",
      "agradecemos",
      "preferência",
      "confiança.",
      "esse",
      "ficou",
      "aqui",
      "curitiba📍",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "procedencia",
      "volkswagen",
      "golftsi",
      "turbo",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)"
    ]
  },
  {
    "id": "DD-XpfSPE_h",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "Desejamos a todos nossos amigos e Clientes um Feliz Natal. Com mu…",
    "description": "Desejamos a todos nossos amigos e Clientes um Feliz Natal. Com muita saúde e paz 🙏🏻🎅🏻\n\n@cwb.repasse_",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DD-XpfSPE_h.jpg",
    "url": "https://www.instagram.com/p/DD-XpfSPE_h/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "desejamos",
      "todos",
      "nossos",
      "amigos",
      "clientes",
      "feliz",
      "natal.",
      "muita",
      "saúde",
      "🙏🏻🎅🏻",
      "cwb.repasse_"
    ]
  },
  {
    "id": "DQJqFQxjaoZ",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "🐎 MERCEDES C-250 SPORT 2.0 TURBO COUPÉ 2017",
    "description": "🐎 MERCEDES C-250 SPORT 2.0 TURBO COUPÉ 2017\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Pericia Cautelar Aprovada\n• ⁠Manual e Chave Reserva\n• ⁠Revisões Recém Feitas\n• ⁠Interna Couro Ótima\n• ⁠Apenas Polimento\n• ⁠IPVA 25 Quitado\n• ⁠4 Pneus Bons\n• ⁠App Car Play\n• ⁠99 MIL KM\n• ⁠Teto Solar\n• ⁠KIT AMG\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 187.000,00\nVALOR$ 147.000💰\n\n40 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 147.000",
    "image": "imagens/cwb.repasse__DQJqFQxjaoZ.jpg",
    "url": "https://www.instagram.com/p/DQJqFQxjaoZ/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "mercedes",
      "c-250",
      "sport",
      "turbo",
      "coupé",
      "2017",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "pericia",
      "cautelar",
      "aprovada",
      "⁠manual",
      "chave",
      "reserva",
      "⁠revisões",
      "recém",
      "feitas",
      "⁠interna",
      "couro",
      "ótima",
      "⁠apenas",
      "polimento",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons"
    ]
  },
  {
    "id": "DDsdfdRv9Xm",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "TIGUAN TSI 2015 VENDIDA ✔️",
    "description": "TIGUAN TSI 2015 VENDIDA ✔️\n\nParabéns ao casal Wagner e Gabrieli pela excelente escolha!\n\nAgradecemos a preferência e confiança 🙏🏻\n\n#seminovos #bomnegocio #carroscuritiba #volkswagen #tiguantsi #abaixodafipe #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DDsdfdRv9Xm.jpg",
    "url": "https://www.instagram.com/p/DDsdfdRv9Xm/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "tiguan",
      "2015",
      "vendida",
      "parabéns",
      "casal",
      "wagner",
      "gabrieli",
      "pela",
      "excelente",
      "escolha!",
      "agradecemos",
      "preferência",
      "confiança",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagen",
      "tiguantsi",
      "abaixodafipe",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DGap3pZRmSw",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "RANGER LIMITED 2019 VENDIDO ✔️",
    "description": "RANGER LIMITED 2019 VENDIDO ✔️\n\nParabéns Fábio pela conquista! Linda caminhonete, fez uma ótima escolha.\n\nEssa vai para Santa Catarina📍\n\n#seminovos #bomnegocio #carroscuritiba #fordranger #caminhonete #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DGap3pZRmSw.jpg",
    "url": "https://www.instagram.com/p/DGap3pZRmSw/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "ranger",
      "limited",
      "2019",
      "vendido",
      "parabéns",
      "fábio",
      "pela",
      "conquista!",
      "linda",
      "caminhonete,",
      "ótima",
      "escolha.",
      "essa",
      "para",
      "santa",
      "catarina📍",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "fordranger",
      "caminhonete",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)"
    ]
  },
  {
    "id": "C_d7UXAPqzb",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "NISSAN LEAF 2022 VENDIDO ✈️",
    "description": "NISSAN LEAF 2022 VENDIDO ✈️\n\nRealmente a tecnologia chegou! Parabéns Moisés pela excelente aquisição.\n\nMais um veículo 100% elétrico.\n\nEsse foi para Florianópolis - SC📍\n\n#seminovos #bomnegocio #carroscuritiba #nissan #elétrico #abaixofipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__C_d7UXAPqzb.jpg",
    "url": "https://www.instagram.com/p/C_d7UXAPqzb/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "nissan",
      "leaf",
      "2022",
      "vendido",
      "realmente",
      "tecnologia",
      "chegou!",
      "parabéns",
      "moisés",
      "pela",
      "excelente",
      "aquisição.",
      "mais",
      "veículo",
      "100%",
      "elétrico.",
      "esse",
      "para",
      "florianópolis",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "nissan",
      "elétrico",
      "abaixofipe"
    ]
  },
  {
    "id": "DDmUObMR3O_",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "VW GOLF GTI 2015 VENDIDO ✔️",
    "description": "VW GOLF GTI 2015 VENDIDO ✔️\n\nParabéns Gustavo pela conquista! Excelente escolha.\n\nEsse foi para PIRAI DO SUL - PR📍\n\n#seminovos #bomnegocio #carroscuritiba #volkswagen #golfgti #stage2 #performance #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DDmUObMR3O_.jpg",
    "url": "https://www.instagram.com/p/DDmUObMR3O_/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "2015",
      "vendido",
      "parabéns",
      "gustavo",
      "pela",
      "conquista!",
      "excelente",
      "escolha.",
      "esse",
      "para",
      "pirai",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagen",
      "golfgti",
      "stage2",
      "performance",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DOBOJ3VDaz6",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "COROLLA XEI 2024 VENDIDO ✔️",
    "description": "COROLLA XEI 2024 VENDIDO ✔️\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\nParabéns José pela conquista! Excelente escolha.\n\n#seminovos #bomnegocio #carroscuritiba #toyota #corollaxei #executivo #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DOBOJ3VDaz6.jpg",
    "url": "https://www.instagram.com/p/DOBOJ3VDaz6/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "corolla",
      "2024",
      "vendido",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "parabéns",
      "josé",
      "pela",
      "conquista!",
      "excelente",
      "escolha.",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "toyota",
      "corollaxei",
      "executivo",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "C_VVxFERBJH",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "NISSAN LEAF ELÉTRICO 2022",
    "description": "NISSAN LEAF ELÉTRICO 2022\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Revisões na Concessionária\n• ⁠Manual e Chave Reserva\n• ⁠Garantia de Fábrica\n• ⁠Apenas Polimento\n• ⁠IPVA 24 Quitado\n• ⁠2 Pneus Bons\n• ⁠Faróis de Led\n• ⁠65 MIL KM\n• ⁠Multimídia\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 140.000,00\nVALOR$ 96.000💰\n\n42 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 96.000",
    "image": "imagens/cwb.repasse__C_VVxFERBJH.jpg",
    "url": "https://www.instagram.com/p/C_VVxFERBJH/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "nissan",
      "leaf",
      "elétrico",
      "2022",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "revisões",
      "concessionária",
      "⁠manual",
      "chave",
      "reserva",
      "⁠garantia",
      "fábrica",
      "⁠apenas",
      "polimento",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠faróis",
      "⁠multimídia",
      "consta",
      "leilão",
      "fipe:",
      "140.000,00",
      "valor$"
    ]
  },
  {
    "id": "DCJ4SdAv60I",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "VOLVO XC60 HÍBRIDA VENDIDA ✈️",
    "description": "VOLVO XC60 HÍBRIDA VENDIDA ✈️\n\nEssa foi para nosso amigo e cliente Rafael! Obrigado irmão pela confiança 👊🏻\n\n#seminovos #bomnegocio #carroscuritiba #premium #volvoxc60 #hibrido #abaixodafipe #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DCJ4SdAv60I.jpg",
    "url": "https://www.instagram.com/p/DCJ4SdAv60I/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "volvo",
      "xc60",
      "híbrida",
      "vendida",
      "essa",
      "para",
      "nosso",
      "amigo",
      "cliente",
      "rafael!",
      "obrigado",
      "irmão",
      "pela",
      "confiança",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "premium",
      "volvoxc60",
      "hibrido",
      "abaixodafipe",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DAms9RuPbpi",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "BMW 328i SPORT 2.0 AUT. 2015",
    "description": "BMW 328i SPORT 2.0 AUT. 2015\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• ⁠Revisões Recém Feitas\n• ⁠Manual do Proprietário\n• ⁠Veículo Inteiro no PPF\n• ⁠Interna Couro Ótima\n• ⁠IPVA 24 Quitado\n• ⁠2 Pneus Bons\n• ⁠90 MIL KM\n• ⁠Multimídia\n• ⁠Blindada\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: 122.000,00\nVALOR$ 97.500💰\n\n25 MIL A BAIXO DA FIPE\n\nCURITIBA📍",
    "price": "R$ 97.500",
    "image": "imagens/cwb.repasse__DAms9RuPbpi.jpg",
    "url": "https://www.instagram.com/p/DAms9RuPbpi/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "328i",
      "sport",
      "aut.",
      "2015",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "⁠revisões",
      "recém",
      "feitas",
      "⁠manual",
      "proprietário",
      "⁠veículo",
      "inteiro",
      "⁠interna",
      "couro",
      "ótima",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠multimídia",
      "⁠blindada",
      "consta",
      "leilão",
      "fipe:",
      "122.000,00"
    ]
  },
  {
    "id": "DNa1VUWturT",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "POLO SEDAN 1.6 2012 VENDIDO ✔️",
    "description": "POLO SEDAN 1.6 2012 VENDIDO ✔️\n\n• Agradecemos a preferência e confiança Felipe!\n\n#seminovos #bomnegocio #carroscuritiba #volkswagem #polosedan #abaixodafipe #vemvctambém\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DNa1VUWturT.jpg",
    "url": "https://www.instagram.com/p/DNa1VUWturT/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "polo",
      "sedan",
      "2012",
      "vendido",
      "agradecemos",
      "preferência",
      "confiança",
      "felipe!",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagem",
      "polosedan",
      "abaixodafipe",
      "vemvctambém",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DSpVEx1jbOK",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "Feliz Natal e Ano Novo a Todos! 🙏🏻",
    "description": "Feliz Natal e Ano Novo a Todos! 🙏🏻",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DSpVEx1jbOK.jpg",
    "url": "https://www.instagram.com/p/DSpVEx1jbOK/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "feliz",
      "natal",
      "novo",
      "todos!"
    ]
  },
  {
    "id": "DOdv3OGjSFR",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "BMW X1 SPORT 2019 VENDIDA ✔️",
    "description": "BMW X1 SPORT 2019 VENDIDA ✔️\n\n🏅Parabéns Marcinho! Excelente escolha.\n\nAgradecemos a preferência e confiança em nosso trabalho.\n\n#seminovospremium #bomnegocio #carroscuritiba #sportmotivation #bmw #cwbrepasse #vemvctambém\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DOdv3OGjSFR.jpg",
    "url": "https://www.instagram.com/p/DOdv3OGjSFR/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "sport",
      "2019",
      "vendida",
      "🏅parabéns",
      "marcinho!",
      "excelente",
      "escolha.",
      "agradecemos",
      "preferência",
      "confiança",
      "nosso",
      "trabalho.",
      "seminovospremium",
      "bomnegocio",
      "carroscuritiba",
      "sportmotivation",
      "bmw",
      "cwbrepasse",
      "vemvctambém",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "DRmgmxtjTvj",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "Hoje fomos recebidos em uma das melhores lojas aqui de Curitiba! …",
    "description": "Hoje fomos recebidos em uma das melhores lojas aqui de Curitiba! 🏎️ @viasohomotors\n\nApenas agradecer pela parceria e atendimento 👊🏼",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DRmgmxtjTvj.jpg",
    "url": "https://www.instagram.com/p/DRmgmxtjTvj/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "hoje",
      "fomos",
      "recebidos",
      "melhores",
      "lojas",
      "aqui",
      "curitiba!",
      "viasohomotors",
      "apenas",
      "agradecer",
      "pela",
      "parceria",
      "atendimento"
    ]
  },
  {
    "id": "DPXEtm4EonQ",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GOLF VARIANT HIGHLINE 1.4 TSI 2015",
    "description": "GOLF VARIANT HIGHLINE 1.4 TSI 2015\n▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃\n\n• Manual e Chave Reserva\n• Revisões Recém Feitas\n• ⁠Interna Couro Ótima\n• ⁠Veículo Impecável\n• ⁠IPVA 25 Quitado\n• ⁠4 Pneus Bons\n• ⁠102 MIL KM\n• ⁠Multimídia\n• ⁠Teto Solar\n\nNÃO CONSTA LEILÃO OU RS\n\nFIPE: ⁠82.000,00\nVALOR$ 72.000💰\n\n• Aceitamos carro de entrada!\n\nCURITIBA📍",
    "price": "R$ 72.000",
    "image": "imagens/cwb.repasse__DPXEtm4EonQ.jpg",
    "url": "https://www.instagram.com/p/DPXEtm4EonQ/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "variant",
      "highline",
      "2015",
      "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃",
      "manual",
      "chave",
      "reserva",
      "revisões",
      "recém",
      "feitas",
      "⁠interna",
      "couro",
      "ótima",
      "⁠veículo",
      "impecável",
      "⁠ipva",
      "quitado",
      "pneus",
      "bons",
      "⁠102",
      "⁠multimídia",
      "⁠teto",
      "solar",
      "consta"
    ]
  },
  {
    "id": "DAL6Ab4Ptro",
    "tipo": "post",
    "store": "@cwb.repasse_",
    "title": "GOLF TSI 2018 VENDIDO ✔️",
    "description": "GOLF TSI 2018 VENDIDO ✔️\n\nMais uma nave entregue! Parabéns Cleison pela excelente escolha.\n\n#seminovos #bomnegocio #carroscuritiba #volkswagen #performance #golftsi #turbo #abaixodafipe #cwbrepasse #vemvctbm\n\n.\n\n.\n\n📲 (41) 99893-2889",
    "price": "Consulte",
    "image": "imagens/cwb.repasse__DAL6Ab4Ptro.jpg",
    "url": "https://www.instagram.com/p/DAL6Ab4Ptro/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "golf",
      "2018",
      "vendido",
      "mais",
      "nave",
      "entregue!",
      "parabéns",
      "cleison",
      "pela",
      "excelente",
      "escolha.",
      "seminovos",
      "bomnegocio",
      "carroscuritiba",
      "volkswagen",
      "performance",
      "golftsi",
      "turbo",
      "abaixodafipe",
      "cwbrepasse",
      "vemvctbm",
      "(41)",
      "99893-2889"
    ]
  },
  {
    "id": "story_cwb.repasse__1773686094",
    "tipo": "story",
    "store": "@cwb.repasse_",
    "title": "Story de @cwb.repasse_",
    "description": "Story capturado em 16/03/2026 15:34 — dura 24h.",
    "price": "Consulte",
    "image": "imagens/story_cwb.repasse__0_1773686094.jpg",
    "url": "https://www.instagram.com/cwb.repasse_/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "story",
      "cwb.repasse_"
    ]
  },
  {
    "id": "DVAzVXWAEuU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Oferta R$40.000",
    "description": "Oferta R$40.000\n\nREPASSE\n\nCIVIC SEDAN EXS 1.8\nKm 150 mil\nAno 2010\n\nFipe\nR$53.118,00\n\nPor\nR$40.000,00\nIpva 2026 em\nAberto",
    "price": "R$40.000",
    "image": "imagens/autopar.repasses_DVAzVXWAEuU.jpg",
    "url": "https://www.instagram.com/p/DVAzVXWAEuU/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "oferta",
      "r$40.000",
      "repasse",
      "civic",
      "sedan",
      "2010",
      "fipe",
      "r$53.118,00",
      "r$40.000,00",
      "ipva",
      "2026",
      "aberto"
    ]
  },
  {
    "id": "DVAtihfgPwU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Jetta 2.0 aspirado",
    "description": "Jetta 2.0 aspirado\nComfortline\n\nAno 2014\nKm 200 registro 160\n\nTrocar capo\nÉ um pára-lama\n\nPneus bons\n\nNão tem leilão\nNão tem sinistro\n\nFipe 65.000\n\nValor 50.000\n\nInterna boa\n\nMotor e câmbio é bom\n\nIpva 26 2 parcelas pagas\nRestante vai em\nAberto",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVAtihfgPwU.jpg",
    "url": "https://www.instagram.com/p/DVAtihfgPwU/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "jetta",
      "aspirado",
      "comfortline",
      "2014",
      "registro",
      "trocar",
      "capo",
      "pára-lama",
      "pneus",
      "bons",
      "leilão",
      "sinistro",
      "fipe",
      "65.000",
      "valor",
      "50.000",
      "interna",
      "motor",
      "câmbio",
      "ipva",
      "parcelas",
      "pagas",
      "restante",
      "aberto"
    ]
  },
  {
    "id": "DVqD9jpjqFU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Repasses AUTOPAR",
    "description": "Repasses AUTOPAR\n\nVendido com vantagem comercial\n\nFIAT UNO FIRE\n4 portas\nKm130 mil\nAno 2016\nBásico\n\nFazer\nTransferência\nPára-choque dianteiro\nDocumento em dia\n\nSem leilão sem sinistro\n\nFipe33.500\n\nRepasse por R$22.000 mil",
    "price": "R$22.000",
    "image": "imagens/autopar.repasses_DVqD9jpjqFU.jpg",
    "url": "https://www.instagram.com/p/DVqD9jpjqFU/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "repasses",
      "autopar",
      "vendido",
      "vantagem",
      "comercial",
      "fiat",
      "fire",
      "portas",
      "km130",
      "2016",
      "básico",
      "fazer",
      "transferência",
      "pára-choque",
      "dianteiro",
      "documento",
      "leilão",
      "sinistro",
      "fipe33.500",
      "repasse",
      "r$22.000"
    ]
  },
  {
    "id": "DVaDKmyABTU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "R$20.000 de margem",
    "description": "R$20.000 de margem",
    "price": "R$20.000",
    "image": "imagens/autopar.repasses_DVaDKmyABTU.jpg",
    "url": "https://www.instagram.com/p/DVaDKmyABTU/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "r$20.000",
      "margem"
    ]
  },
  {
    "id": "DVAtEqsAOXU",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Ka hatch 1.0 2021",
    "description": "Ka hatch 1.0 2021\nCompleto\nAr trincando\nPneus bons\nCarro com muita qualidade\nZero de mecânica\nKm 80.000\nGastos do retoque parachoque traseiro\nFipe 50.500\n\nPreciso de 43.500\n\nTRANSFERÊNCIA IMEDIATA DE PRODUTIVIDADE",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVAtEqsAOXU.jpg",
    "url": "https://www.instagram.com/p/DVAtEqsAOXU/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "hatch",
      "2021",
      "completo",
      "trincando",
      "pneus",
      "bons",
      "carro",
      "muita",
      "qualidade",
      "zero",
      "mecânica",
      "80.000",
      "gastos",
      "retoque",
      "parachoque",
      "traseiro",
      "fipe",
      "50.500",
      "preciso",
      "43.500",
      "transferência",
      "imediata",
      "produtividade"
    ]
  },
  {
    "id": "DVAyP9ogHTn",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vera Cruz 7 lugares",
    "description": "Vera Cruz 7 lugares\nV6!\nAno 2008\nFipe 47.000\nValor 28.990 pra torrar!\n18 mil abaixo ds fipe!\nCom teto solar.\nZero para andar.\nMecânica em dia , (\ncliente gastou 8.000 e vai me mandar as notas\nInterna bancos dianteiros com couro pouco desgastados.\nCarro muito filé para andar.\nCarro é revisado, mas mesmo assim não vendemos Carro com garantia.",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVAyP9ogHTn.jpg",
    "url": "https://www.instagram.com/p/DVAyP9ogHTn/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vera",
      "cruz",
      "lugares",
      "2008",
      "fipe",
      "47.000",
      "valor",
      "28.990",
      "torrar!",
      "abaixo",
      "fipe!",
      "teto",
      "solar.",
      "zero",
      "para",
      "andar.",
      "mecânica",
      "cliente",
      "gastou",
      "8.000",
      "mandar",
      "notas",
      "interna",
      "bancos",
      "dianteiros"
    ]
  },
  {
    "id": "DVE1WsNETLF",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nAUTOPAR REPASSES\n\nHynday ix35\nAno 2015\n\nFipe 70.000\nValor 57.000\n\nGasta com pneus meia vida\n\nSem leilão\nSem sinistro\n\nIpva 2 parcela paga\n\nCARRO BOM DE VERDADE",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVE1WsNETLF.jpg",
    "url": "https://www.instagram.com/p/DVE1WsNETLF/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "autopar",
      "repasses",
      "hynday",
      "ix35",
      "2015",
      "fipe",
      "70.000",
      "valor",
      "57.000",
      "gasta",
      "pneus",
      "meia",
      "vida",
      "leilão",
      "sinistro",
      "ipva",
      "parcela",
      "paga",
      "carro",
      "verdade"
    ]
  },
  {
    "id": "DUg3SR_AFAy",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vw t-cross",
    "description": "Vw t-cross\nAno 2020\nFipe 105.500\nValor 95.000 mil\nHighline 1.4\nKm 118 mil\nSem leilão\nSem sinistro\nCautelar aprovada\nPneus bons\nInterna zera\nDe lata 1 peça pra pintar",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DUg3SR_AFAy.jpg",
    "url": "https://www.instagram.com/p/DUg3SR_AFAy/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "t-cross",
      "2020",
      "fipe",
      "105.500",
      "valor",
      "95.000",
      "highline",
      "leilão",
      "sinistro",
      "cautelar",
      "aprovada",
      "pneus",
      "bons",
      "interna",
      "zera",
      "lata",
      "peça",
      "pintar"
    ]
  },
  {
    "id": "DVAtUKPAEi6",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nRENALT DUSTER\nDYNAMIC 2013/2013\nKm160k\n\nSem leilão sem sinistro\n\nFipe\nR$46.500\nPor R$30.000\n\nMargem R$16.500",
    "price": "R$46.500",
    "image": "imagens/autopar.repasses_DVAtUKPAEi6.jpg",
    "url": "https://www.instagram.com/p/DVAtUKPAEi6/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "renalt",
      "duster",
      "dynamic",
      "2013/2013",
      "km160k",
      "leilão",
      "sinistro",
      "fipe",
      "r$46.500",
      "r$30.000",
      "margem",
      "r$16.500"
    ]
  },
  {
    "id": "DVAuFpFAMvx",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nPRISMA LT\nano 2012\nKM 170 mil\n\nFipe\nR$29.200\n\nPor\nR$19.000\n\n10 mil de margem\n\nSem leilão sem sinistro",
    "price": "R$29.200",
    "image": "imagens/autopar.repasses_DVAuFpFAMvx.jpg",
    "url": "https://www.instagram.com/p/DVAuFpFAMvx/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "prisma",
      "2012",
      "fipe",
      "r$29.200",
      "r$19.000",
      "margem",
      "leilão",
      "sinistro"
    ]
  },
  {
    "id": "DT_pVIGgNtW",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nChevrolet ônix\n\nAno 2023\nVersão LT2\nKm100 mil único dono\n\nMultimídia\nRodas de liga leve\nChave de prensenca\n\nFipe 66.000\n\nValor 52.000 mil\n\nIpva 2026 já está pago integral\n\nCarro de único dono\n\nApenas retocar 2 pára-choque\n\nNão é batido aprova em\nPerícia",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DT_pVIGgNtW.jpg",
    "url": "https://www.instagram.com/p/DT_pVIGgNtW/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "chevrolet",
      "ônix",
      "2023",
      "versão",
      "km100",
      "único",
      "dono",
      "multimídia",
      "rodas",
      "liga",
      "leve",
      "chave",
      "prensenca",
      "fipe",
      "66.000",
      "valor",
      "52.000",
      "ipva",
      "2026",
      "está",
      "pago",
      "integral",
      "carro",
      "único"
    ]
  },
  {
    "id": "DUg2Es6kT8g",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Só R$9.000 mil",
    "description": "Só R$9.000 mil\n\nChama (41)9.9104-4503",
    "price": "R$9.000",
    "image": "imagens/autopar.repasses_DUg2Es6kT8g.jpg",
    "url": "https://www.instagram.com/p/DUg2Es6kT8g/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "r$9.000",
      "chama",
      "(41)9.9104-4503"
    ]
  },
  {
    "id": "DVAxOxKgBng",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "AUTOPAR REPASSES",
    "description": "AUTOPAR REPASSES\n\nBiz 125 ks\n2011\nKm 40 mil\n\nFipe R$9.500\n\nPor 8.300",
    "price": "R$9.500",
    "image": "imagens/autopar.repasses_DVAxOxKgBng.jpg",
    "url": "https://www.instagram.com/p/DVAxOxKgBng/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "2011",
      "fipe",
      "r$9.500",
      "8.300"
    ]
  },
  {
    "id": "DT_nZFngDdc",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\nHonda fit\n\nCarro de cliente não vai ficar muito tempo por aqui consultar antes de vir\n\nHonda fit\n\nAno 2009\n\nFipe 39.000\n\nValor 25.000 mil\n\n❌Tem rs no dok❌\n\nDetalhado em vídeo\n\nHigienizar interna\n\nAr não gela\n\nPara brisa trincado\n\nSuspensão boa",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DT_nZFngDdc.jpg",
    "url": "https://www.instagram.com/p/DT_nZFngDdc/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "honda",
      "carro",
      "cliente",
      "ficar",
      "muito",
      "tempo",
      "aqui",
      "consultar",
      "antes",
      "honda",
      "2009",
      "fipe",
      "39.000",
      "valor",
      "25.000",
      "❌tem",
      "dok❌",
      "detalhado",
      "vídeo",
      "higienizar",
      "interna",
      "gela",
      "para",
      "brisa"
    ]
  },
  {
    "id": "DVWC59_gPTZ",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nAUTOPAR REPASSES\n\nCitroen C3 ATTRACTIVE\nKM 220 mil\n\nÚnico dono\n\nCarro sem defeitos\n\nFipe\nR$54.500\nPor R$42.000",
    "price": "R$54.500",
    "image": "imagens/autopar.repasses_DVWC59_gPTZ.jpg",
    "url": "https://www.instagram.com/p/DVWC59_gPTZ/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "autopar",
      "repasses",
      "citroen",
      "attractive",
      "único",
      "dono",
      "carro",
      "defeitos",
      "fipe",
      "r$54.500",
      "r$42.000"
    ]
  },
  {
    "id": "DVWEZeWAGoW",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "OFERTA DE RESPASSE",
    "description": "OFERTA DE RESPASSE\nVANTAGEM COMERCIAL\n\nAUTOPAR REPASSES\n\nONIX LT TURBO\n2025\n\nSem leilão sem sinistro\nCautelar aprovará\nDoc 2026 quitado\n4 pneus ótimos\nAr gelado\nCâmera de ré\n\nFazer\nBico do capô\nPára-choque dianteiro\nRisco leve no pára-lama\n\nMargem de 15.852\n\nFipe R$85.850\nPor R$70.000\nTed ou pix\n\n#repasses #autoparrepasses #curitiba\n#brasil🇧🇷 #abaixodafipe",
    "price": "R$85.850",
    "image": "imagens/autopar.repasses_DVWEZeWAGoW.jpg",
    "url": "https://www.instagram.com/p/DVWEZeWAGoW/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "oferta",
      "respasse",
      "vantagem",
      "comercial",
      "autopar",
      "repasses",
      "onix",
      "turbo",
      "2025",
      "leilão",
      "sinistro",
      "cautelar",
      "aprovará",
      "2026",
      "quitado",
      "pneus",
      "ótimos",
      "gelado",
      "câmera",
      "fazer",
      "bico",
      "capô",
      "pára-choque",
      "dianteiro",
      "risco"
    ]
  },
  {
    "id": "DV5s1_lAGvx",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "REPASSE AUTOPAR",
    "description": "REPASSE AUTOPAR\n\nBMW\n125i M Sport/Active Flex 2.0 TB\nAut. 5p\n\n2014 Gasolina\n\nFipe R$ 109.228,00\n\nPor R$91.000\n\nSem leilão sem sinistro",
    "price": "R$ 109.228,00",
    "image": "imagens/autopar.repasses_DV5s1_lAGvx.jpg",
    "url": "https://www.instagram.com/p/DV5s1_lAGvx/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "repasse",
      "autopar",
      "125i",
      "sport/active",
      "flex",
      "aut.",
      "2014",
      "gasolina",
      "fipe",
      "109.228,00",
      "r$91.000",
      "leilão",
      "sinistro"
    ]
  },
  {
    "id": "DVzfLXAAO1d",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Tracker premier",
    "description": "Tracker premier\n\nMotor 1.4 turbo 4 cilindros\n\nFipe 84.000 mil\n\nValor 67.000 mil\n\nConsta rs no dok\n\nMas tem aparência",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVzfLXAAO1d.jpg",
    "url": "https://www.instagram.com/p/DVzfLXAAO1d/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "tracker",
      "premier",
      "motor",
      "turbo",
      "cilindros",
      "fipe",
      "84.000",
      "valor",
      "67.000",
      "consta",
      "aparência"
    ]
  },
  {
    "id": "DUg2iB3kYhX",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Repasse",
    "description": "Repasse\n\nX Sara Picasso\n1.6 mec\n2007\nKM 180 mil\n\nAr não gelou\nPra andar é boa\nPneus bons\nMotor funcionando\nClaro que tem 19 anos de uso\n\nFipe\nR$15.000\nPor 10 mil mais despesas",
    "price": "R$15.000",
    "image": "imagens/autopar.repasses_DUg2iB3kYhX.jpg",
    "url": "https://www.instagram.com/p/DUg2iB3kYhX/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "repasse",
      "sara",
      "picasso",
      "2007",
      "gelou",
      "andar",
      "pneus",
      "bons",
      "motor",
      "funcionando",
      "claro",
      "anos",
      "fipe",
      "r$15.000",
      "mais",
      "despesas"
    ]
  },
  {
    "id": "DT_lReIgH-9",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nAUTOPAR REPASSES\nRua OMILIO MONTEIRO SOARES 1686 Fanny Curitiba Paraná\n\n(41)9.9104-4503\nJociel\n(41)9.9104-4302\nRoniel\n\nOportunidade\n\nTucson\n\nFipe 38.000\n\nValor 25.000 mil\n\nDespesa 2 peças pra pintar\n\nSuspensão bate a frente\n\nAr não gela\n\nSem leilão\n\nSem sinistro\n\nIpva 2026 pago",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DT_lReIgH-9.jpg",
    "url": "https://www.instagram.com/p/DT_lReIgH-9/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "autopar",
      "repasses",
      "omilio",
      "monteiro",
      "soares",
      "1686",
      "fanny",
      "curitiba",
      "paraná",
      "(41)9.9104-4503",
      "jociel",
      "(41)9.9104-4302",
      "roniel",
      "oportunidade",
      "tucson",
      "fipe",
      "38.000",
      "valor",
      "25.000",
      "despesa",
      "peças",
      "pintar",
      "suspensão",
      "bate"
    ]
  },
  {
    "id": "DVAwI64gPdM",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "Vendido",
    "description": "Vendido\n\nFord FUSION",
    "price": "Consulte",
    "image": "imagens/autopar.repasses_DVAwI64gPdM.jpg",
    "url": "https://www.instagram.com/p/DVAwI64gPdM/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "vendido",
      "ford",
      "fusion"
    ]
  },
  {
    "id": "DVqPdbAgA4b",
    "tipo": "post",
    "store": "@autopar.repasses",
    "title": "✅ AUTOPAR REPASSES",
    "description": "✅ AUTOPAR REPASSES\n\nNÃO SERÁ LIBERADO A RETIRADA DO CARRO SEM O COMUNICADO DE VENDAS\n(Não concedemos prazo pra transferência)\n\nEndereço do pátio\n📍 Rua Omilio Monteiro Soares, 1686 – Fanny – Curitiba/PR\n\nMARCA: FIAT\nMODELO: ARGO flex\n🚙 VERSÃO: 1.0\nANO 2024/2025\nKm 50 mil\n\n✅ SEM SINISTRO\n✅SEM LEILÃO\n✅ CAUTELAR\n\n📊 FIPE: R$72.200\n\nR$13.200 a baixo da Fipe\n\n💰 Repasse: R$59.000\n\nVenda fora do estado acr",
    "price": "R$72.200",
    "image": "imagens/autopar.repasses_DVqPdbAgA4b.jpg",
    "url": "https://www.instagram.com/p/DVqPdbAgA4b/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "autopar",
      "repasses",
      "será",
      "liberado",
      "retirada",
      "carro",
      "comunicado",
      "vendas",
      "(não",
      "concedemos",
      "prazo",
      "transferência)",
      "endereço",
      "pátio",
      "omilio",
      "monteiro",
      "soares,",
      "1686",
      "fanny",
      "curitiba/pr",
      "marca:",
      "fiat",
      "modelo:",
      "argo",
      "flex"
    ]
  },
  {
    "id": "story_autopar.repasses_1773686246",
    "tipo": "story",
    "store": "@autopar.repasses",
    "title": "Story de @autopar.repasses",
    "description": "Story capturado em 16/03/2026 15:37 — dura 24h.",
    "price": "Consulte",
    "image": "imagens/story_autopar.repasses_0_1773686246.jpg",
    "url": "https://www.instagram.com/autopar.repasses/",
    "date": "16/03/2026",
    "likes": 0,
    "keywords": [
      "story",
      "autopar.repasses"
    ]
  }
];
